// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"krishblog/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldID, id))
}

// UploaderID applies equality check predicate on the "uploader_id" field. It's identical to UploaderIDEQ.
func UploaderID(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUploaderID, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldURL, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldStorageKey, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldFilename, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalName, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSizeBytes, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldHeight, v))
}

// DurationSec applies equality check predicate on the "duration_sec" field. It's identical to DurationSecEQ.
func DurationSec(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldDurationSec, v))
}

// ThumbnailURL applies equality check predicate on the "thumbnail_url" field. It's identical to ThumbnailURLEQ.
func ThumbnailURL(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldThumbnailURL, v))
}

// AltText applies equality check predicate on the "alt_text" field. It's identical to AltTextEQ.
func AltText(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAltText, v))
}

// Caption applies equality check predicate on the "caption" field. It's identical to CaptionEQ.
func Caption(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaption, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// UploaderIDEQ applies the EQ predicate on the "uploader_id" field.
func UploaderIDEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUploaderID, v))
}

// UploaderIDNEQ applies the NEQ predicate on the "uploader_id" field.
func UploaderIDNEQ(v uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldUploaderID, v))
}

// UploaderIDIn applies the In predicate on the "uploader_id" field.
func UploaderIDIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldUploaderID, vs...))
}

// UploaderIDNotIn applies the NotIn predicate on the "uploader_id" field.
func UploaderIDNotIn(vs ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldUploaderID, vs...))
}

// UploaderIDIsNil applies the IsNil predicate on the "uploader_id" field.
func UploaderIDIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldUploaderID))
}

// UploaderIDNotNil applies the NotNil predicate on the "uploader_id" field.
func UploaderIDNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldUploaderID))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldURL, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldStorageKey, v))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldFilename, v))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldOriginalName, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldMimeType, v))
}

// AssetTypeEQ applies the EQ predicate on the "asset_type" field.
func AssetTypeEQ(v AssetType) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAssetType, v))
}

// AssetTypeNEQ applies the NEQ predicate on the "asset_type" field.
func AssetTypeNEQ(v AssetType) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldAssetType, v))
}

// AssetTypeIn applies the In predicate on the "asset_type" field.
func AssetTypeIn(vs ...AssetType) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldAssetType, vs...))
}

// AssetTypeNotIn applies the NotIn predicate on the "asset_type" field.
func AssetTypeNotIn(vs ...AssetType) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldAssetType, vs...))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldSizeBytes, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldHeight))
}

// DurationSecEQ applies the EQ predicate on the "duration_sec" field.
func DurationSecEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldDurationSec, v))
}

// DurationSecNEQ applies the NEQ predicate on the "duration_sec" field.
func DurationSecNEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldDurationSec, v))
}

// DurationSecIn applies the In predicate on the "duration_sec" field.
func DurationSecIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldDurationSec, vs...))
}

// DurationSecNotIn applies the NotIn predicate on the "duration_sec" field.
func DurationSecNotIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldDurationSec, vs...))
}

// DurationSecGT applies the GT predicate on the "duration_sec" field.
func DurationSecGT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldDurationSec, v))
}

// DurationSecGTE applies the GTE predicate on the "duration_sec" field.
func DurationSecGTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldDurationSec, v))
}

// DurationSecLT applies the LT predicate on the "duration_sec" field.
func DurationSecLT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldDurationSec, v))
}

// DurationSecLTE applies the LTE predicate on the "duration_sec" field.
func DurationSecLTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldDurationSec, v))
}

// DurationSecIsNil applies the IsNil predicate on the "duration_sec" field.
func DurationSecIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldDurationSec))
}

// DurationSecNotNil applies the NotNil predicate on the "duration_sec" field.
func DurationSecNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldDurationSec))
}

// ThumbnailURLEQ applies the EQ predicate on the "thumbnail_url" field.
func ThumbnailURLEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldThumbnailURL, v))
}

// ThumbnailURLNEQ applies the NEQ predicate on the "thumbnail_url" field.
func ThumbnailURLNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldThumbnailURL, v))
}

// ThumbnailURLIn applies the In predicate on the "thumbnail_url" field.
func ThumbnailURLIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldThumbnailURL, vs...))
}

// ThumbnailURLNotIn applies the NotIn predicate on the "thumbnail_url" field.
func ThumbnailURLNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldThumbnailURL, vs...))
}

// ThumbnailURLGT applies the GT predicate on the "thumbnail_url" field.
func ThumbnailURLGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldThumbnailURL, v))
}

// ThumbnailURLGTE applies the GTE predicate on the "thumbnail_url" field.
func ThumbnailURLGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldThumbnailURL, v))
}

// ThumbnailURLLT applies the LT predicate on the "thumbnail_url" field.
func ThumbnailURLLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldThumbnailURL, v))
}

// ThumbnailURLLTE applies the LTE predicate on the "thumbnail_url" field.
func ThumbnailURLLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldThumbnailURL, v))
}

// ThumbnailURLContains applies the Contains predicate on the "thumbnail_url" field.
func ThumbnailURLContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldThumbnailURL, v))
}

// ThumbnailURLHasPrefix applies the HasPrefix predicate on the "thumbnail_url" field.
func ThumbnailURLHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldThumbnailURL, v))
}

// ThumbnailURLHasSuffix applies the HasSuffix predicate on the "thumbnail_url" field.
func ThumbnailURLHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldThumbnailURL, v))
}

// ThumbnailURLIsNil applies the IsNil predicate on the "thumbnail_url" field.
func ThumbnailURLIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldThumbnailURL))
}

// ThumbnailURLNotNil applies the NotNil predicate on the "thumbnail_url" field.
func ThumbnailURLNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldThumbnailURL))
}

// ThumbnailURLEqualFold applies the EqualFold predicate on the "thumbnail_url" field.
func ThumbnailURLEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldThumbnailURL, v))
}

// ThumbnailURLContainsFold applies the ContainsFold predicate on the "thumbnail_url" field.
func ThumbnailURLContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldThumbnailURL, v))
}

// AltTextEQ applies the EQ predicate on the "alt_text" field.
func AltTextEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldAltText, v))
}

// AltTextNEQ applies the NEQ predicate on the "alt_text" field.
func AltTextNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldAltText, v))
}

// AltTextIn applies the In predicate on the "alt_text" field.
func AltTextIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldAltText, vs...))
}

// AltTextNotIn applies the NotIn predicate on the "alt_text" field.
func AltTextNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldAltText, vs...))
}

// AltTextGT applies the GT predicate on the "alt_text" field.
func AltTextGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldAltText, v))
}

// AltTextGTE applies the GTE predicate on the "alt_text" field.
func AltTextGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldAltText, v))
}

// AltTextLT applies the LT predicate on the "alt_text" field.
func AltTextLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldAltText, v))
}

// AltTextLTE applies the LTE predicate on the "alt_text" field.
func AltTextLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldAltText, v))
}

// AltTextContains applies the Contains predicate on the "alt_text" field.
func AltTextContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldAltText, v))
}

// AltTextHasPrefix applies the HasPrefix predicate on the "alt_text" field.
func AltTextHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldAltText, v))
}

// AltTextHasSuffix applies the HasSuffix predicate on the "alt_text" field.
func AltTextHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldAltText, v))
}

// AltTextIsNil applies the IsNil predicate on the "alt_text" field.
func AltTextIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldAltText))
}

// AltTextNotNil applies the NotNil predicate on the "alt_text" field.
func AltTextNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldAltText))
}

// AltTextEqualFold applies the EqualFold predicate on the "alt_text" field.
func AltTextEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldAltText, v))
}

// AltTextContainsFold applies the ContainsFold predicate on the "alt_text" field.
func AltTextContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldAltText, v))
}

// CaptionEQ applies the EQ predicate on the "caption" field.
func CaptionEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaption, v))
}

// CaptionNEQ applies the NEQ predicate on the "caption" field.
func CaptionNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCaption, v))
}

// CaptionIn applies the In predicate on the "caption" field.
func CaptionIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCaption, vs...))
}

// CaptionNotIn applies the NotIn predicate on the "caption" field.
func CaptionNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCaption, vs...))
}

// CaptionGT applies the GT predicate on the "caption" field.
func CaptionGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCaption, v))
}

// CaptionGTE applies the GTE predicate on the "caption" field.
func CaptionGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCaption, v))
}

// CaptionLT applies the LT predicate on the "caption" field.
func CaptionLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCaption, v))
}

// CaptionLTE applies the LTE predicate on the "caption" field.
func CaptionLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCaption, v))
}

// CaptionContains applies the Contains predicate on the "caption" field.
func CaptionContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldCaption, v))
}

// CaptionHasPrefix applies the HasPrefix predicate on the "caption" field.
func CaptionHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldCaption, v))
}

// CaptionHasSuffix applies the HasSuffix predicate on the "caption" field.
func CaptionHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldCaption, v))
}

// CaptionIsNil applies the IsNil predicate on the "caption" field.
func CaptionIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldCaption))
}

// CaptionNotNil applies the NotNil predicate on the "caption" field.
func CaptionNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldCaption))
}

// CaptionEqualFold applies the EqualFold predicate on the "caption" field.
func CaptionEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldCaption, v))
}

// CaptionContainsFold applies the ContainsFold predicate on the "caption" field.
func CaptionContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldCaption, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUploader applies the HasEdge predicate on the "uploader" edge.
func HasUploader() predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploaderTable, UploaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploaderWith applies the HasEdge predicate on the "uploader" edge with a given conditions (other predicates).
func HasUploaderWith(preds ...predicate.User) predicate.MediaAsset {
	return predicate.MediaAsset(func(s *sql.Selector) {
		step := newUploaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.NotPredicates(p))
}
