// Code generated by ent, DO NOT EDIT.

package analyticsevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the analyticsevent type in the database.
	Label = "analytics_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldDevice holds the string denoting the device field in the database.
	FieldDevice = "device"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldReferrer holds the string denoting the referrer field in the database.
	FieldReferrer = "referrer"
	// FieldScrollPct holds the string denoting the scroll_pct field in the database.
	FieldScrollPct = "scroll_pct"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// Table holds the table name of the analyticsevent in the database.
	Table = "analytics_events"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "analytics_events"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_id"
)

// Columns holds all SQL columns for analyticsevent fields.
var Columns = []string{
	FieldID,
	FieldPostID,
	FieldEventType,
	FieldSessionID,
	FieldDevice,
	FieldCountry,
	FieldPath,
	FieldReferrer,
	FieldScrollPct,
	FieldDurationMs,
	FieldMetadata,
	FieldTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// ReferrerValidator is a validator for the "referrer" field. It is called by the builders before save.
	ReferrerValidator func(string) error
	// ScrollPctValidator is a validator for the "scroll_pct" field. It is called by the builders before save.
	ScrollPctValidator func(int) error
	// DurationMsValidator is a validator for the "duration_ms" field. It is called by the builders before save.
	DurationMsValidator func(int) error
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypePageView     EventType = "page_view"
	EventTypePostView     EventType = "post_view"
	EventTypeScrollDepth  EventType = "scroll_depth"
	EventTypeClick        EventType = "click"
	EventTypeSearch       EventType = "search"
	EventTypeSessionStart EventType = "session_start"
	EventTypeSessionEnd   EventType = "session_end"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypePageView, EventTypePostView, EventTypeScrollDepth, EventTypeClick, EventTypeSearch, EventTypeSessionStart, EventTypeSessionEnd:
		return nil
	default:
		return fmt.Errorf("analyticsevent: invalid enum value for event_type field: %q", et)
	}
}

// Device defines the type for the "device" enum field.
type Device string

// DeviceUnknown is the default value of the Device enum.
const DefaultDevice = DeviceUnknown

// Device values.
const (
	DeviceDesktop Device = "desktop"
	DeviceTablet  Device = "tablet"
	DeviceMobile  Device = "mobile"
	DeviceUnknown Device = "unknown"
)

func (d Device) String() string {
	return string(d)
}

// DeviceValidator is a validator for the "device" field enum values. It is called by the builders before save.
func DeviceValidator(d Device) error {
	switch d {
	case DeviceDesktop, DeviceTablet, DeviceMobile, DeviceUnknown:
		return nil
	default:
		return fmt.Errorf("analyticsevent: invalid enum value for device field: %q", d)
	}
}

// OrderOption defines the ordering options for the AnalyticsEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByDevice orders the results by the device field.
func ByDevice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDevice, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByReferrer orders the results by the referrer field.
func ByReferrer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrer, opts...).ToFunc()
}

// ByScrollPct orders the results by the scroll_pct field.
func ByScrollPct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrollPct, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByPostField orders the results by post field.
func ByPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostStep(), sql.OrderByField(field, opts...))
	}
}
func newPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
	)
}
