// Code generated by ent, DO NOT EDIT.

package analyticsevent

import (
	"krishblog/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldID, id))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPostID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldSessionID, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldCountry, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPath, v))
}

// Referrer applies equality check predicate on the "referrer" field. It's identical to ReferrerEQ.
func Referrer(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldReferrer, v))
}

// ScrollPct applies equality check predicate on the "scroll_pct" field. It's identical to ScrollPctEQ.
func ScrollPct(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldScrollPct, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldDurationMs, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldTimestamp, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...uuid.UUID) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDIsNil applies the IsNil predicate on the "post_id" field.
func PostIDIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldPostID))
}

// PostIDNotNil applies the NotNil predicate on the "post_id" field.
func PostIDNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldPostID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v EventType) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v EventType) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...EventType) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...EventType) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// DeviceEQ applies the EQ predicate on the "device" field.
func DeviceEQ(v Device) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldDevice, v))
}

// DeviceNEQ applies the NEQ predicate on the "device" field.
func DeviceNEQ(v Device) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldDevice, v))
}

// DeviceIn applies the In predicate on the "device" field.
func DeviceIn(vs ...Device) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldDevice, vs...))
}

// DeviceNotIn applies the NotIn predicate on the "device" field.
func DeviceNotIn(vs ...Device) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldDevice, vs...))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryIsNil applies the IsNil predicate on the "country" field.
func CountryIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldCountry))
}

// CountryNotNil applies the NotNil predicate on the "country" field.
func CountryNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldCountry))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldCountry, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldPath, v))
}

// ReferrerEQ applies the EQ predicate on the "referrer" field.
func ReferrerEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldReferrer, v))
}

// ReferrerNEQ applies the NEQ predicate on the "referrer" field.
func ReferrerNEQ(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldReferrer, v))
}

// ReferrerIn applies the In predicate on the "referrer" field.
func ReferrerIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldReferrer, vs...))
}

// ReferrerNotIn applies the NotIn predicate on the "referrer" field.
func ReferrerNotIn(vs ...string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldReferrer, vs...))
}

// ReferrerGT applies the GT predicate on the "referrer" field.
func ReferrerGT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldReferrer, v))
}

// ReferrerGTE applies the GTE predicate on the "referrer" field.
func ReferrerGTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldReferrer, v))
}

// ReferrerLT applies the LT predicate on the "referrer" field.
func ReferrerLT(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldReferrer, v))
}

// ReferrerLTE applies the LTE predicate on the "referrer" field.
func ReferrerLTE(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldReferrer, v))
}

// ReferrerContains applies the Contains predicate on the "referrer" field.
func ReferrerContains(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContains(FieldReferrer, v))
}

// ReferrerHasPrefix applies the HasPrefix predicate on the "referrer" field.
func ReferrerHasPrefix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasPrefix(FieldReferrer, v))
}

// ReferrerHasSuffix applies the HasSuffix predicate on the "referrer" field.
func ReferrerHasSuffix(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldHasSuffix(FieldReferrer, v))
}

// ReferrerIsNil applies the IsNil predicate on the "referrer" field.
func ReferrerIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldReferrer))
}

// ReferrerNotNil applies the NotNil predicate on the "referrer" field.
func ReferrerNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldReferrer))
}

// ReferrerEqualFold applies the EqualFold predicate on the "referrer" field.
func ReferrerEqualFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEqualFold(FieldReferrer, v))
}

// ReferrerContainsFold applies the ContainsFold predicate on the "referrer" field.
func ReferrerContainsFold(v string) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldContainsFold(FieldReferrer, v))
}

// ScrollPctEQ applies the EQ predicate on the "scroll_pct" field.
func ScrollPctEQ(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldScrollPct, v))
}

// ScrollPctNEQ applies the NEQ predicate on the "scroll_pct" field.
func ScrollPctNEQ(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldScrollPct, v))
}

// ScrollPctIn applies the In predicate on the "scroll_pct" field.
func ScrollPctIn(vs ...int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldScrollPct, vs...))
}

// ScrollPctNotIn applies the NotIn predicate on the "scroll_pct" field.
func ScrollPctNotIn(vs ...int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldScrollPct, vs...))
}

// ScrollPctGT applies the GT predicate on the "scroll_pct" field.
func ScrollPctGT(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldScrollPct, v))
}

// ScrollPctGTE applies the GTE predicate on the "scroll_pct" field.
func ScrollPctGTE(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldScrollPct, v))
}

// ScrollPctLT applies the LT predicate on the "scroll_pct" field.
func ScrollPctLT(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldScrollPct, v))
}

// ScrollPctLTE applies the LTE predicate on the "scroll_pct" field.
func ScrollPctLTE(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldScrollPct, v))
}

// ScrollPctIsNil applies the IsNil predicate on the "scroll_pct" field.
func ScrollPctIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldScrollPct))
}

// ScrollPctNotNil applies the NotNil predicate on the "scroll_pct" field.
func ScrollPctNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldScrollPct))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldDurationMs))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotNull(FieldMetadata))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.FieldLTE(FieldTimestamp, v))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnalyticsEvent) predicate.AnalyticsEvent {
	return predicate.AnalyticsEvent(sql.NotPredicates(p))
}
