// Code generated by ent, DO NOT EDIT.

package post

import (
	"krishblog/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// SectionID applies equality check predicate on the "section_id" field. It's identical to SectionIDEQ.
func SectionID(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSectionID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldAuthorID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSlug, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSummary, v))
}

// CoverImage applies equality check predicate on the "cover_image" field. It's identical to CoverImageEQ.
func CoverImage(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageAlt applies equality check predicate on the "cover_image_alt" field. It's identical to CoverImageAltEQ.
func CoverImageAlt(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverImageAlt, v))
}

// Published applies equality check predicate on the "published" field. It's identical to PublishedEQ.
func Published(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublished, v))
}

// ReadTime applies equality check predicate on the "read_time" field. It's identical to ReadTimeEQ.
func ReadTime(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldReadTime, v))
}

// WordCount applies equality check predicate on the "word_count" field. It's identical to WordCountEQ.
func WordCount(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldWordCount, v))
}

// IsFeatured applies equality check predicate on the "is_featured" field. It's identical to IsFeaturedEQ.
func IsFeatured(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsFeatured, v))
}

// MetaTitle applies equality check predicate on the "meta_title" field. It's identical to MetaTitleEQ.
func MetaTitle(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaDesc applies equality check predicate on the "meta_desc" field. It's identical to MetaDescEQ.
func MetaDesc(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMetaDesc, v))
}

// OgImage applies equality check predicate on the "og_image" field. It's identical to OgImageEQ.
func OgImage(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldOgImage, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishedAt, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldScheduledAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// SectionIDEQ applies the EQ predicate on the "section_id" field.
func SectionIDEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSectionID, v))
}

// SectionIDNEQ applies the NEQ predicate on the "section_id" field.
func SectionIDNEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldSectionID, v))
}

// SectionIDIn applies the In predicate on the "section_id" field.
func SectionIDIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldSectionID, vs...))
}

// SectionIDNotIn applies the NotIn predicate on the "section_id" field.
func SectionIDNotIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldSectionID, vs...))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...uuid.UUID) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldAuthorID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldSlug, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldSummary, v))
}

// CoverImageEQ applies the EQ predicate on the "cover_image" field.
func CoverImageEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageNEQ applies the NEQ predicate on the "cover_image" field.
func CoverImageNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCoverImage, v))
}

// CoverImageIn applies the In predicate on the "cover_image" field.
func CoverImageIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCoverImage, vs...))
}

// CoverImageNotIn applies the NotIn predicate on the "cover_image" field.
func CoverImageNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCoverImage, vs...))
}

// CoverImageGT applies the GT predicate on the "cover_image" field.
func CoverImageGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCoverImage, v))
}

// CoverImageGTE applies the GTE predicate on the "cover_image" field.
func CoverImageGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCoverImage, v))
}

// CoverImageLT applies the LT predicate on the "cover_image" field.
func CoverImageLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCoverImage, v))
}

// CoverImageLTE applies the LTE predicate on the "cover_image" field.
func CoverImageLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCoverImage, v))
}

// CoverImageContains applies the Contains predicate on the "cover_image" field.
func CoverImageContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldCoverImage, v))
}

// CoverImageHasPrefix applies the HasPrefix predicate on the "cover_image" field.
func CoverImageHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldCoverImage, v))
}

// CoverImageHasSuffix applies the HasSuffix predicate on the "cover_image" field.
func CoverImageHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldCoverImage, v))
}

// CoverImageIsNil applies the IsNil predicate on the "cover_image" field.
func CoverImageIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldCoverImage))
}

// CoverImageNotNil applies the NotNil predicate on the "cover_image" field.
func CoverImageNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldCoverImage))
}

// CoverImageEqualFold applies the EqualFold predicate on the "cover_image" field.
func CoverImageEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldCoverImage, v))
}

// CoverImageContainsFold applies the ContainsFold predicate on the "cover_image" field.
func CoverImageContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldCoverImage, v))
}

// CoverImageAltEQ applies the EQ predicate on the "cover_image_alt" field.
func CoverImageAltEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCoverImageAlt, v))
}

// CoverImageAltNEQ applies the NEQ predicate on the "cover_image_alt" field.
func CoverImageAltNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCoverImageAlt, v))
}

// CoverImageAltIn applies the In predicate on the "cover_image_alt" field.
func CoverImageAltIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCoverImageAlt, vs...))
}

// CoverImageAltNotIn applies the NotIn predicate on the "cover_image_alt" field.
func CoverImageAltNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCoverImageAlt, vs...))
}

// CoverImageAltGT applies the GT predicate on the "cover_image_alt" field.
func CoverImageAltGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCoverImageAlt, v))
}

// CoverImageAltGTE applies the GTE predicate on the "cover_image_alt" field.
func CoverImageAltGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCoverImageAlt, v))
}

// CoverImageAltLT applies the LT predicate on the "cover_image_alt" field.
func CoverImageAltLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCoverImageAlt, v))
}

// CoverImageAltLTE applies the LTE predicate on the "cover_image_alt" field.
func CoverImageAltLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCoverImageAlt, v))
}

// CoverImageAltContains applies the Contains predicate on the "cover_image_alt" field.
func CoverImageAltContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldCoverImageAlt, v))
}

// CoverImageAltHasPrefix applies the HasPrefix predicate on the "cover_image_alt" field.
func CoverImageAltHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldCoverImageAlt, v))
}

// CoverImageAltHasSuffix applies the HasSuffix predicate on the "cover_image_alt" field.
func CoverImageAltHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldCoverImageAlt, v))
}

// CoverImageAltIsNil applies the IsNil predicate on the "cover_image_alt" field.
func CoverImageAltIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldCoverImageAlt))
}

// CoverImageAltNotNil applies the NotNil predicate on the "cover_image_alt" field.
func CoverImageAltNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldCoverImageAlt))
}

// CoverImageAltEqualFold applies the EqualFold predicate on the "cover_image_alt" field.
func CoverImageAltEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldCoverImageAlt, v))
}

// CoverImageAltContainsFold applies the ContainsFold predicate on the "cover_image_alt" field.
func CoverImageAltContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldCoverImageAlt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldStatus, vs...))
}

// PublishedEQ applies the EQ predicate on the "published" field.
func PublishedEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublished, v))
}

// PublishedNEQ applies the NEQ predicate on the "published" field.
func PublishedNEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPublished, v))
}

// ReadTimeEQ applies the EQ predicate on the "read_time" field.
func ReadTimeEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldReadTime, v))
}

// ReadTimeNEQ applies the NEQ predicate on the "read_time" field.
func ReadTimeNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldReadTime, v))
}

// ReadTimeIn applies the In predicate on the "read_time" field.
func ReadTimeIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldReadTime, vs...))
}

// ReadTimeNotIn applies the NotIn predicate on the "read_time" field.
func ReadTimeNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldReadTime, vs...))
}

// ReadTimeGT applies the GT predicate on the "read_time" field.
func ReadTimeGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldReadTime, v))
}

// ReadTimeGTE applies the GTE predicate on the "read_time" field.
func ReadTimeGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldReadTime, v))
}

// ReadTimeLT applies the LT predicate on the "read_time" field.
func ReadTimeLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldReadTime, v))
}

// ReadTimeLTE applies the LTE predicate on the "read_time" field.
func ReadTimeLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldReadTime, v))
}

// WordCountEQ applies the EQ predicate on the "word_count" field.
func WordCountEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldWordCount, v))
}

// WordCountNEQ applies the NEQ predicate on the "word_count" field.
func WordCountNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldWordCount, v))
}

// WordCountIn applies the In predicate on the "word_count" field.
func WordCountIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldWordCount, vs...))
}

// WordCountNotIn applies the NotIn predicate on the "word_count" field.
func WordCountNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldWordCount, vs...))
}

// WordCountGT applies the GT predicate on the "word_count" field.
func WordCountGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldWordCount, v))
}

// WordCountGTE applies the GTE predicate on the "word_count" field.
func WordCountGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldWordCount, v))
}

// WordCountLT applies the LT predicate on the "word_count" field.
func WordCountLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldWordCount, v))
}

// WordCountLTE applies the LTE predicate on the "word_count" field.
func WordCountLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldWordCount, v))
}

// IsFeaturedEQ applies the EQ predicate on the "is_featured" field.
func IsFeaturedEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsFeatured, v))
}

// IsFeaturedNEQ applies the NEQ predicate on the "is_featured" field.
func IsFeaturedNEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldIsFeatured, v))
}

// MetaTitleEQ applies the EQ predicate on the "meta_title" field.
func MetaTitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMetaTitle, v))
}

// MetaTitleNEQ applies the NEQ predicate on the "meta_title" field.
func MetaTitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldMetaTitle, v))
}

// MetaTitleIn applies the In predicate on the "meta_title" field.
func MetaTitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldMetaTitle, vs...))
}

// MetaTitleNotIn applies the NotIn predicate on the "meta_title" field.
func MetaTitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldMetaTitle, vs...))
}

// MetaTitleGT applies the GT predicate on the "meta_title" field.
func MetaTitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldMetaTitle, v))
}

// MetaTitleGTE applies the GTE predicate on the "meta_title" field.
func MetaTitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldMetaTitle, v))
}

// MetaTitleLT applies the LT predicate on the "meta_title" field.
func MetaTitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldMetaTitle, v))
}

// MetaTitleLTE applies the LTE predicate on the "meta_title" field.
func MetaTitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldMetaTitle, v))
}

// MetaTitleContains applies the Contains predicate on the "meta_title" field.
func MetaTitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldMetaTitle, v))
}

// MetaTitleHasPrefix applies the HasPrefix predicate on the "meta_title" field.
func MetaTitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldMetaTitle, v))
}

// MetaTitleHasSuffix applies the HasSuffix predicate on the "meta_title" field.
func MetaTitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldMetaTitle, v))
}

// MetaTitleIsNil applies the IsNil predicate on the "meta_title" field.
func MetaTitleIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldMetaTitle))
}

// MetaTitleNotNil applies the NotNil predicate on the "meta_title" field.
func MetaTitleNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldMetaTitle))
}

// MetaTitleEqualFold applies the EqualFold predicate on the "meta_title" field.
func MetaTitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldMetaTitle, v))
}

// MetaTitleContainsFold applies the ContainsFold predicate on the "meta_title" field.
func MetaTitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldMetaTitle, v))
}

// MetaDescEQ applies the EQ predicate on the "meta_desc" field.
func MetaDescEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldMetaDesc, v))
}

// MetaDescNEQ applies the NEQ predicate on the "meta_desc" field.
func MetaDescNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldMetaDesc, v))
}

// MetaDescIn applies the In predicate on the "meta_desc" field.
func MetaDescIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldMetaDesc, vs...))
}

// MetaDescNotIn applies the NotIn predicate on the "meta_desc" field.
func MetaDescNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldMetaDesc, vs...))
}

// MetaDescGT applies the GT predicate on the "meta_desc" field.
func MetaDescGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldMetaDesc, v))
}

// MetaDescGTE applies the GTE predicate on the "meta_desc" field.
func MetaDescGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldMetaDesc, v))
}

// MetaDescLT applies the LT predicate on the "meta_desc" field.
func MetaDescLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldMetaDesc, v))
}

// MetaDescLTE applies the LTE predicate on the "meta_desc" field.
func MetaDescLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldMetaDesc, v))
}

// MetaDescContains applies the Contains predicate on the "meta_desc" field.
func MetaDescContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldMetaDesc, v))
}

// MetaDescHasPrefix applies the HasPrefix predicate on the "meta_desc" field.
func MetaDescHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldMetaDesc, v))
}

// MetaDescHasSuffix applies the HasSuffix predicate on the "meta_desc" field.
func MetaDescHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldMetaDesc, v))
}

// MetaDescIsNil applies the IsNil predicate on the "meta_desc" field.
func MetaDescIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldMetaDesc))
}

// MetaDescNotNil applies the NotNil predicate on the "meta_desc" field.
func MetaDescNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldMetaDesc))
}

// MetaDescEqualFold applies the EqualFold predicate on the "meta_desc" field.
func MetaDescEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldMetaDesc, v))
}

// MetaDescContainsFold applies the ContainsFold predicate on the "meta_desc" field.
func MetaDescContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldMetaDesc, v))
}

// OgImageEQ applies the EQ predicate on the "og_image" field.
func OgImageEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldOgImage, v))
}

// OgImageNEQ applies the NEQ predicate on the "og_image" field.
func OgImageNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldOgImage, v))
}

// OgImageIn applies the In predicate on the "og_image" field.
func OgImageIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldOgImage, vs...))
}

// OgImageNotIn applies the NotIn predicate on the "og_image" field.
func OgImageNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldOgImage, vs...))
}

// OgImageGT applies the GT predicate on the "og_image" field.
func OgImageGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldOgImage, v))
}

// OgImageGTE applies the GTE predicate on the "og_image" field.
func OgImageGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldOgImage, v))
}

// OgImageLT applies the LT predicate on the "og_image" field.
func OgImageLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldOgImage, v))
}

// OgImageLTE applies the LTE predicate on the "og_image" field.
func OgImageLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldOgImage, v))
}

// OgImageContains applies the Contains predicate on the "og_image" field.
func OgImageContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldOgImage, v))
}

// OgImageHasPrefix applies the HasPrefix predicate on the "og_image" field.
func OgImageHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldOgImage, v))
}

// OgImageHasSuffix applies the HasSuffix predicate on the "og_image" field.
func OgImageHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldOgImage, v))
}

// OgImageIsNil applies the IsNil predicate on the "og_image" field.
func OgImageIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldOgImage))
}

// OgImageNotNil applies the NotNil predicate on the "og_image" field.
func OgImageNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldOgImage))
}

// OgImageEqualFold applies the EqualFold predicate on the "og_image" field.
func OgImageEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldOgImage, v))
}

// OgImageContainsFold applies the ContainsFold predicate on the "og_image" field.
func OgImageContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldOgImage, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPublishedAt))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldScheduledAt, v))
}

// ScheduledAtIsNil applies the IsNil predicate on the "scheduled_at" field.
func ScheduledAtIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldScheduledAt))
}

// ScheduledAtNotNil applies the NotNil predicate on the "scheduled_at" field.
func ScheduledAtNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldScheduledAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSection applies the HasEdge predicate on the "section" edge.
func HasSection() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SectionTable, SectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSectionWith applies the HasEdge predicate on the "section" edge with a given conditions (other predicates).
func HasSectionWith(preds ...predicate.Section) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newSectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlocks applies the HasEdge predicate on the "blocks" edge.
func HasBlocks() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BlocksTable, BlocksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlocksWith applies the HasEdge predicate on the "blocks" edge with a given conditions (other predicates).
func HasBlocksWith(preds ...predicate.PostBlock) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newBlocksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnalyticsEvents applies the HasEdge predicate on the "analytics_events" edge.
func HasAnalyticsEvents() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnalyticsEventsTable, AnalyticsEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnalyticsEventsWith applies the HasEdge predicate on the "analytics_events" edge with a given conditions (other predicates).
func HasAnalyticsEventsWith(preds ...predicate.AnalyticsEvent) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newAnalyticsEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
