// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"krishblog/ent/analyticsevent"
	"krishblog/ent/post"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AnalyticsEvent is the model entity for the AnalyticsEvent schema.
type AnalyticsEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Post being viewed — nil for non-post page views
	PostID *uuid.UUID `json:"post_id,omitempty"`
	// Discriminator for event shape
	EventType analyticsevent.EventType `json:"event_type,omitempty"`
	// Anonymous session UUID stored in a first-party cookie
	SessionID string `json:"session_id,omitempty"`
	// Derived from User-Agent
	Device analyticsevent.Device `json:"device,omitempty"`
	// ISO 3166-1 alpha-2 country code from Cloudflare CF-IPCountry header
	Country string `json:"country,omitempty"`
	// URL path of the page that fired the event
	Path string `json:"path,omitempty"`
	// HTTP Referer header value
	Referrer string `json:"referrer,omitempty"`
	// Scroll depth percentage — populated for scroll_depth events
	ScrollPct *int `json:"scroll_pct,omitempty"`
	// Session or page duration in milliseconds
	DurationMs *int `json:"duration_ms,omitempty"`
	// Event-specific extra payload
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// When the event was recorded
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnalyticsEventQuery when eager-loading is set.
	Edges        AnalyticsEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnalyticsEventEdges holds the relations/edges for other nodes in the graph.
type AnalyticsEventEdges struct {
	// Post this event belongs to — optional
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnalyticsEventEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnalyticsEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case analyticsevent.FieldPostID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case analyticsevent.FieldMetadata:
			values[i] = new([]byte)
		case analyticsevent.FieldScrollPct, analyticsevent.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case analyticsevent.FieldEventType, analyticsevent.FieldSessionID, analyticsevent.FieldDevice, analyticsevent.FieldCountry, analyticsevent.FieldPath, analyticsevent.FieldReferrer:
			values[i] = new(sql.NullString)
		case analyticsevent.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case analyticsevent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnalyticsEvent fields.
func (_m *AnalyticsEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case analyticsevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case analyticsevent.FieldPostID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = new(uuid.UUID)
				*_m.PostID = *value.S.(*uuid.UUID)
			}
		case analyticsevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = analyticsevent.EventType(value.String)
			}
		case analyticsevent.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case analyticsevent.FieldDevice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device", values[i])
			} else if value.Valid {
				_m.Device = analyticsevent.Device(value.String)
			}
		case analyticsevent.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case analyticsevent.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case analyticsevent.FieldReferrer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referrer", values[i])
			} else if value.Valid {
				_m.Referrer = value.String
			}
		case analyticsevent.FieldScrollPct:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scroll_pct", values[i])
			} else if value.Valid {
				_m.ScrollPct = new(int)
				*_m.ScrollPct = int(value.Int64)
			}
		case analyticsevent.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case analyticsevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case analyticsevent.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnalyticsEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AnalyticsEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the AnalyticsEvent entity.
func (_m *AnalyticsEvent) QueryPost() *PostQuery {
	return NewAnalyticsEventClient(_m.config).QueryPost(_m)
}

// Update returns a builder for updating this AnalyticsEvent.
// Note that you need to call AnalyticsEvent.Unwrap() before calling this method if this AnalyticsEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnalyticsEvent) Update() *AnalyticsEventUpdateOne {
	return NewAnalyticsEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnalyticsEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnalyticsEvent) Unwrap() *AnalyticsEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnalyticsEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnalyticsEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AnalyticsEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.PostID; v != nil {
		builder.WriteString("post_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventType))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("device=")
	builder.WriteString(fmt.Sprintf("%v", _m.Device))
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("referrer=")
	builder.WriteString(_m.Referrer)
	builder.WriteString(", ")
	if v := _m.ScrollPct; v != nil {
		builder.WriteString("scroll_pct=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AnalyticsEvents is a parsable slice of AnalyticsEvent.
type AnalyticsEvents []*AnalyticsEvent
