// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/analyticsevent"
	"krishblog/ent/post"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnalyticsEventCreate is the builder for creating a AnalyticsEvent entity.
type AnalyticsEventCreate struct {
	config
	mutation *AnalyticsEventMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (_c *AnalyticsEventCreate) SetPostID(v uuid.UUID) *AnalyticsEventCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillablePostID(v *uuid.UUID) *AnalyticsEventCreate {
	if v != nil {
		_c.SetPostID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *AnalyticsEventCreate) SetEventType(v analyticsevent.EventType) *AnalyticsEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AnalyticsEventCreate) SetSessionID(v string) *AnalyticsEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetDevice sets the "device" field.
func (_c *AnalyticsEventCreate) SetDevice(v analyticsevent.Device) *AnalyticsEventCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableDevice(v *analyticsevent.Device) *AnalyticsEventCreate {
	if v != nil {
		_c.SetDevice(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *AnalyticsEventCreate) SetCountry(v string) *AnalyticsEventCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableCountry(v *string) *AnalyticsEventCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AnalyticsEventCreate) SetPath(v string) *AnalyticsEventCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetReferrer sets the "referrer" field.
func (_c *AnalyticsEventCreate) SetReferrer(v string) *AnalyticsEventCreate {
	_c.mutation.SetReferrer(v)
	return _c
}

// SetNillableReferrer sets the "referrer" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableReferrer(v *string) *AnalyticsEventCreate {
	if v != nil {
		_c.SetReferrer(*v)
	}
	return _c
}

// SetScrollPct sets the "scroll_pct" field.
func (_c *AnalyticsEventCreate) SetScrollPct(v int) *AnalyticsEventCreate {
	_c.mutation.SetScrollPct(v)
	return _c
}

// SetNillableScrollPct sets the "scroll_pct" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableScrollPct(v *int) *AnalyticsEventCreate {
	if v != nil {
		_c.SetScrollPct(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AnalyticsEventCreate) SetDurationMs(v int) *AnalyticsEventCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableDurationMs(v *int) *AnalyticsEventCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AnalyticsEventCreate) SetMetadata(v map[string]interface{}) *AnalyticsEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AnalyticsEventCreate) SetTimestamp(v time.Time) *AnalyticsEventCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableTimestamp(v *time.Time) *AnalyticsEventCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AnalyticsEventCreate) SetID(v uuid.UUID) *AnalyticsEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AnalyticsEventCreate) SetNillableID(v *uuid.UUID) *AnalyticsEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *AnalyticsEventCreate) SetPost(v *Post) *AnalyticsEventCreate {
	return _c.SetPostID(v.ID)
}

// Mutation returns the AnalyticsEventMutation object of the builder.
func (_c *AnalyticsEventCreate) Mutation() *AnalyticsEventMutation {
	return _c.mutation
}

// Save creates the AnalyticsEvent in the database.
func (_c *AnalyticsEventCreate) Save(ctx context.Context) (*AnalyticsEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnalyticsEventCreate) SaveX(ctx context.Context) *AnalyticsEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnalyticsEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnalyticsEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnalyticsEventCreate) defaults() {
	if _, ok := _c.mutation.Device(); !ok {
		v := analyticsevent.DefaultDevice
		_c.mutation.SetDevice(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := analyticsevent.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := analyticsevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnalyticsEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AnalyticsEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := analyticsevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AnalyticsEvent.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := analyticsevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Device(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required field "AnalyticsEvent.device"`)}
	}
	if v, ok := _c.mutation.Device(); ok {
		if err := analyticsevent.DeviceValidator(v); err != nil {
			return &ValidationError{Name: "device", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.device": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := analyticsevent.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AnalyticsEvent.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := analyticsevent.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Referrer(); ok {
		if err := analyticsevent.ReferrerValidator(v); err != nil {
			return &ValidationError{Name: "referrer", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.referrer": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ScrollPct(); ok {
		if err := analyticsevent.ScrollPctValidator(v); err != nil {
			return &ValidationError{Name: "scroll_pct", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.scroll_pct": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DurationMs(); ok {
		if err := analyticsevent.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.duration_ms": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AnalyticsEvent.timestamp"`)}
	}
	return nil
}

func (_c *AnalyticsEventCreate) sqlSave(ctx context.Context) (*AnalyticsEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnalyticsEventCreate) createSpec() (*AnalyticsEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AnalyticsEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(analyticsevent.Table, sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(analyticsevent.FieldEventType, field.TypeEnum, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(analyticsevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(analyticsevent.FieldDevice, field.TypeEnum, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(analyticsevent.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(analyticsevent.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Referrer(); ok {
		_spec.SetField(analyticsevent.FieldReferrer, field.TypeString, value)
		_node.Referrer = value
	}
	if value, ok := _c.mutation.ScrollPct(); ok {
		_spec.SetField(analyticsevent.FieldScrollPct, field.TypeInt, value)
		_node.ScrollPct = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(analyticsevent.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(analyticsevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(analyticsevent.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyticsevent.PostTable,
			Columns: []string{analyticsevent.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnalyticsEventCreateBulk is the builder for creating many AnalyticsEvent entities in bulk.
type AnalyticsEventCreateBulk struct {
	config
	err      error
	builders []*AnalyticsEventCreate
}

// Save creates the AnalyticsEvent entities in the database.
func (_c *AnalyticsEventCreateBulk) Save(ctx context.Context) ([]*AnalyticsEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnalyticsEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnalyticsEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnalyticsEventCreateBulk) SaveX(ctx context.Context) []*AnalyticsEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnalyticsEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnalyticsEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
