// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/analyticsevent"
	"krishblog/ent/post"
	"krishblog/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnalyticsEventUpdate is the builder for updating AnalyticsEvent entities.
type AnalyticsEventUpdate struct {
	config
	hooks    []Hook
	mutation *AnalyticsEventMutation
}

// Where appends a list predicates to the AnalyticsEventUpdate builder.
func (_u *AnalyticsEventUpdate) Where(ps ...predicate.AnalyticsEvent) *AnalyticsEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *AnalyticsEventUpdate) SetPostID(v uuid.UUID) *AnalyticsEventUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillablePostID(v *uuid.UUID) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// ClearPostID clears the value of the "post_id" field.
func (_u *AnalyticsEventUpdate) ClearPostID() *AnalyticsEventUpdate {
	_u.mutation.ClearPostID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *AnalyticsEventUpdate) SetEventType(v analyticsevent.EventType) *AnalyticsEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableEventType(v *analyticsevent.EventType) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AnalyticsEventUpdate) SetSessionID(v string) *AnalyticsEventUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableSessionID(v *string) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *AnalyticsEventUpdate) SetDevice(v analyticsevent.Device) *AnalyticsEventUpdate {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableDevice(v *analyticsevent.Device) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *AnalyticsEventUpdate) SetCountry(v string) *AnalyticsEventUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableCountry(v *string) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *AnalyticsEventUpdate) ClearCountry() *AnalyticsEventUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetPath sets the "path" field.
func (_u *AnalyticsEventUpdate) SetPath(v string) *AnalyticsEventUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillablePath(v *string) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetReferrer sets the "referrer" field.
func (_u *AnalyticsEventUpdate) SetReferrer(v string) *AnalyticsEventUpdate {
	_u.mutation.SetReferrer(v)
	return _u
}

// SetNillableReferrer sets the "referrer" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableReferrer(v *string) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetReferrer(*v)
	}
	return _u
}

// ClearReferrer clears the value of the "referrer" field.
func (_u *AnalyticsEventUpdate) ClearReferrer() *AnalyticsEventUpdate {
	_u.mutation.ClearReferrer()
	return _u
}

// SetScrollPct sets the "scroll_pct" field.
func (_u *AnalyticsEventUpdate) SetScrollPct(v int) *AnalyticsEventUpdate {
	_u.mutation.ResetScrollPct()
	_u.mutation.SetScrollPct(v)
	return _u
}

// SetNillableScrollPct sets the "scroll_pct" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableScrollPct(v *int) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetScrollPct(*v)
	}
	return _u
}

// AddScrollPct adds value to the "scroll_pct" field.
func (_u *AnalyticsEventUpdate) AddScrollPct(v int) *AnalyticsEventUpdate {
	_u.mutation.AddScrollPct(v)
	return _u
}

// ClearScrollPct clears the value of the "scroll_pct" field.
func (_u *AnalyticsEventUpdate) ClearScrollPct() *AnalyticsEventUpdate {
	_u.mutation.ClearScrollPct()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AnalyticsEventUpdate) SetDurationMs(v int) *AnalyticsEventUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AnalyticsEventUpdate) SetNillableDurationMs(v *int) *AnalyticsEventUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AnalyticsEventUpdate) AddDurationMs(v int) *AnalyticsEventUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AnalyticsEventUpdate) ClearDurationMs() *AnalyticsEventUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AnalyticsEventUpdate) SetMetadata(v map[string]interface{}) *AnalyticsEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AnalyticsEventUpdate) ClearMetadata() *AnalyticsEventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *AnalyticsEventUpdate) SetPost(v *Post) *AnalyticsEventUpdate {
	return _u.SetPostID(v.ID)
}

// Mutation returns the AnalyticsEventMutation object of the builder.
func (_u *AnalyticsEventUpdate) Mutation() *AnalyticsEventMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *AnalyticsEventUpdate) ClearPost() *AnalyticsEventUpdate {
	_u.mutation.ClearPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnalyticsEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnalyticsEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnalyticsEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnalyticsEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnalyticsEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := analyticsevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := analyticsevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Device(); ok {
		if err := analyticsevent.DeviceValidator(v); err != nil {
			return &ValidationError{Name: "device", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.device": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := analyticsevent.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := analyticsevent.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referrer(); ok {
		if err := analyticsevent.ReferrerValidator(v); err != nil {
			return &ValidationError{Name: "referrer", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScrollPct(); ok {
		if err := analyticsevent.ScrollPctValidator(v); err != nil {
			return &ValidationError{Name: "scroll_pct", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.scroll_pct": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := analyticsevent.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.duration_ms": %w`, err)}
		}
	}
	return nil
}

func (_u *AnalyticsEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(analyticsevent.Table, analyticsevent.Columns, sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(analyticsevent.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(analyticsevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(analyticsevent.FieldDevice, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(analyticsevent.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(analyticsevent.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(analyticsevent.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referrer(); ok {
		_spec.SetField(analyticsevent.FieldReferrer, field.TypeString, value)
	}
	if _u.mutation.ReferrerCleared() {
		_spec.ClearField(analyticsevent.FieldReferrer, field.TypeString)
	}
	if value, ok := _u.mutation.ScrollPct(); ok {
		_spec.SetField(analyticsevent.FieldScrollPct, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScrollPct(); ok {
		_spec.AddField(analyticsevent.FieldScrollPct, field.TypeInt, value)
	}
	if _u.mutation.ScrollPctCleared() {
		_spec.ClearField(analyticsevent.FieldScrollPct, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(analyticsevent.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(analyticsevent.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(analyticsevent.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(analyticsevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(analyticsevent.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyticsevent.PostTable,
			Columns: []string{analyticsevent.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyticsevent.PostTable,
			Columns: []string{analyticsevent.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{analyticsevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnalyticsEventUpdateOne is the builder for updating a single AnalyticsEvent entity.
type AnalyticsEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnalyticsEventMutation
}

// SetPostID sets the "post_id" field.
func (_u *AnalyticsEventUpdateOne) SetPostID(v uuid.UUID) *AnalyticsEventUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillablePostID(v *uuid.UUID) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// ClearPostID clears the value of the "post_id" field.
func (_u *AnalyticsEventUpdateOne) ClearPostID() *AnalyticsEventUpdateOne {
	_u.mutation.ClearPostID()
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *AnalyticsEventUpdateOne) SetEventType(v analyticsevent.EventType) *AnalyticsEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableEventType(v *analyticsevent.EventType) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AnalyticsEventUpdateOne) SetSessionID(v string) *AnalyticsEventUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableSessionID(v *string) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *AnalyticsEventUpdateOne) SetDevice(v analyticsevent.Device) *AnalyticsEventUpdateOne {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableDevice(v *analyticsevent.Device) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *AnalyticsEventUpdateOne) SetCountry(v string) *AnalyticsEventUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableCountry(v *string) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *AnalyticsEventUpdateOne) ClearCountry() *AnalyticsEventUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetPath sets the "path" field.
func (_u *AnalyticsEventUpdateOne) SetPath(v string) *AnalyticsEventUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillablePath(v *string) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetReferrer sets the "referrer" field.
func (_u *AnalyticsEventUpdateOne) SetReferrer(v string) *AnalyticsEventUpdateOne {
	_u.mutation.SetReferrer(v)
	return _u
}

// SetNillableReferrer sets the "referrer" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableReferrer(v *string) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetReferrer(*v)
	}
	return _u
}

// ClearReferrer clears the value of the "referrer" field.
func (_u *AnalyticsEventUpdateOne) ClearReferrer() *AnalyticsEventUpdateOne {
	_u.mutation.ClearReferrer()
	return _u
}

// SetScrollPct sets the "scroll_pct" field.
func (_u *AnalyticsEventUpdateOne) SetScrollPct(v int) *AnalyticsEventUpdateOne {
	_u.mutation.ResetScrollPct()
	_u.mutation.SetScrollPct(v)
	return _u
}

// SetNillableScrollPct sets the "scroll_pct" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableScrollPct(v *int) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetScrollPct(*v)
	}
	return _u
}

// AddScrollPct adds value to the "scroll_pct" field.
func (_u *AnalyticsEventUpdateOne) AddScrollPct(v int) *AnalyticsEventUpdateOne {
	_u.mutation.AddScrollPct(v)
	return _u
}

// ClearScrollPct clears the value of the "scroll_pct" field.
func (_u *AnalyticsEventUpdateOne) ClearScrollPct() *AnalyticsEventUpdateOne {
	_u.mutation.ClearScrollPct()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AnalyticsEventUpdateOne) SetDurationMs(v int) *AnalyticsEventUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AnalyticsEventUpdateOne) SetNillableDurationMs(v *int) *AnalyticsEventUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AnalyticsEventUpdateOne) AddDurationMs(v int) *AnalyticsEventUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AnalyticsEventUpdateOne) ClearDurationMs() *AnalyticsEventUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AnalyticsEventUpdateOne) SetMetadata(v map[string]interface{}) *AnalyticsEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AnalyticsEventUpdateOne) ClearMetadata() *AnalyticsEventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *AnalyticsEventUpdateOne) SetPost(v *Post) *AnalyticsEventUpdateOne {
	return _u.SetPostID(v.ID)
}

// Mutation returns the AnalyticsEventMutation object of the builder.
func (_u *AnalyticsEventUpdateOne) Mutation() *AnalyticsEventMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *AnalyticsEventUpdateOne) ClearPost() *AnalyticsEventUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// Where appends a list predicates to the AnalyticsEventUpdate builder.
func (_u *AnalyticsEventUpdateOne) Where(ps ...predicate.AnalyticsEvent) *AnalyticsEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnalyticsEventUpdateOne) Select(field string, fields ...string) *AnalyticsEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnalyticsEvent entity.
func (_u *AnalyticsEventUpdateOne) Save(ctx context.Context) (*AnalyticsEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnalyticsEventUpdateOne) SaveX(ctx context.Context) *AnalyticsEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnalyticsEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnalyticsEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnalyticsEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := analyticsevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := analyticsevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Device(); ok {
		if err := analyticsevent.DeviceValidator(v); err != nil {
			return &ValidationError{Name: "device", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.device": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := analyticsevent.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := analyticsevent.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referrer(); ok {
		if err := analyticsevent.ReferrerValidator(v); err != nil {
			return &ValidationError{Name: "referrer", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScrollPct(); ok {
		if err := analyticsevent.ScrollPctValidator(v); err != nil {
			return &ValidationError{Name: "scroll_pct", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.scroll_pct": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := analyticsevent.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AnalyticsEvent.duration_ms": %w`, err)}
		}
	}
	return nil
}

func (_u *AnalyticsEventUpdateOne) sqlSave(ctx context.Context) (_node *AnalyticsEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(analyticsevent.Table, analyticsevent.Columns, sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnalyticsEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, analyticsevent.FieldID)
		for _, f := range fields {
			if !analyticsevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != analyticsevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(analyticsevent.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(analyticsevent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(analyticsevent.FieldDevice, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(analyticsevent.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(analyticsevent.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(analyticsevent.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referrer(); ok {
		_spec.SetField(analyticsevent.FieldReferrer, field.TypeString, value)
	}
	if _u.mutation.ReferrerCleared() {
		_spec.ClearField(analyticsevent.FieldReferrer, field.TypeString)
	}
	if value, ok := _u.mutation.ScrollPct(); ok {
		_spec.SetField(analyticsevent.FieldScrollPct, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScrollPct(); ok {
		_spec.AddField(analyticsevent.FieldScrollPct, field.TypeInt, value)
	}
	if _u.mutation.ScrollPctCleared() {
		_spec.ClearField(analyticsevent.FieldScrollPct, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(analyticsevent.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(analyticsevent.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(analyticsevent.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(analyticsevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(analyticsevent.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyticsevent.PostTable,
			Columns: []string{analyticsevent.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   analyticsevent.PostTable,
			Columns: []string{analyticsevent.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AnalyticsEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{analyticsevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
