// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/mediaasset"
	"krishblog/ent/predicate"
	"krishblog/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MediaAssetUpdate is the builder for updating MediaAsset entities.
type MediaAssetUpdate struct {
	config
	hooks    []Hook
	mutation *MediaAssetMutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdate) Where(ps ...predicate.MediaAsset) *MediaAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *MediaAssetUpdate) SetUploaderID(v uuid.UUID) *MediaAssetUpdate {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableUploaderID(v *uuid.UUID) *MediaAssetUpdate {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// ClearUploaderID clears the value of the "uploader_id" field.
func (_u *MediaAssetUpdate) ClearUploaderID() *MediaAssetUpdate {
	_u.mutation.ClearUploaderID()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaAssetUpdate) SetURL(v string) *MediaAssetUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableURL(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *MediaAssetUpdate) SetStorageKey(v string) *MediaAssetUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableStorageKey(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *MediaAssetUpdate) SetFilename(v string) *MediaAssetUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableFilename(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaAssetUpdate) SetOriginalName(v string) *MediaAssetUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableOriginalName(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdate) SetMimeType(v string) *MediaAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableMimeType(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *MediaAssetUpdate) SetAssetType(v mediaasset.AssetType) *MediaAssetUpdate {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableAssetType(v *mediaasset.AssetType) *MediaAssetUpdate {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *MediaAssetUpdate) SetSizeBytes(v int64) *MediaAssetUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableSizeBytes(v *int64) *MediaAssetUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *MediaAssetUpdate) AddSizeBytes(v int64) *MediaAssetUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaAssetUpdate) SetWidth(v int) *MediaAssetUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableWidth(v *int) *MediaAssetUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaAssetUpdate) AddWidth(v int) *MediaAssetUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaAssetUpdate) ClearWidth() *MediaAssetUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaAssetUpdate) SetHeight(v int) *MediaAssetUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableHeight(v *int) *MediaAssetUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaAssetUpdate) AddHeight(v int) *MediaAssetUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaAssetUpdate) ClearHeight() *MediaAssetUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetDurationSec sets the "duration_sec" field.
func (_u *MediaAssetUpdate) SetDurationSec(v float64) *MediaAssetUpdate {
	_u.mutation.ResetDurationSec()
	_u.mutation.SetDurationSec(v)
	return _u
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableDurationSec(v *float64) *MediaAssetUpdate {
	if v != nil {
		_u.SetDurationSec(*v)
	}
	return _u
}

// AddDurationSec adds value to the "duration_sec" field.
func (_u *MediaAssetUpdate) AddDurationSec(v float64) *MediaAssetUpdate {
	_u.mutation.AddDurationSec(v)
	return _u
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (_u *MediaAssetUpdate) ClearDurationSec() *MediaAssetUpdate {
	_u.mutation.ClearDurationSec()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaAssetUpdate) SetThumbnailURL(v string) *MediaAssetUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableThumbnailURL(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaAssetUpdate) ClearThumbnailURL() *MediaAssetUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *MediaAssetUpdate) SetAltText(v string) *MediaAssetUpdate {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableAltText(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *MediaAssetUpdate) ClearAltText() *MediaAssetUpdate {
	_u.mutation.ClearAltText()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *MediaAssetUpdate) SetCaption(v string) *MediaAssetUpdate {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableCaption(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *MediaAssetUpdate) ClearCaption() *MediaAssetUpdate {
	_u.mutation.ClearCaption()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MediaAssetUpdate) SetMetadata(v map[string]interface{}) *MediaAssetUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MediaAssetUpdate) ClearMetadata() *MediaAssetUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *MediaAssetUpdate) SetUploader(v *User) *MediaAssetUpdate {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdate) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *MediaAssetUpdate) ClearUploader() *MediaAssetUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := mediaasset.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := mediaasset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := mediaasset.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := mediaasset.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetType(); ok {
		if err := mediaasset.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := mediaasset.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := mediaasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := mediaasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSec(); ok {
		if err := mediaasset.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.duration_sec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailURL(); ok {
		if err := mediaasset.ThumbnailURLValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.thumbnail_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := mediaasset.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Caption(); ok {
		if err := mediaasset.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.caption": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mediaasset.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(mediaasset.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(mediaasset.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(mediaasset.FieldAssetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(mediaasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(mediaasset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(mediaasset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(mediaasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(mediaasset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(mediaasset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationSec(); ok {
		_spec.SetField(mediaasset.FieldDurationSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationSec(); ok {
		_spec.AddField(mediaasset.FieldDurationSec, field.TypeFloat64, value)
	}
	if _u.mutation.DurationSecCleared() {
		_spec.ClearField(mediaasset.FieldDurationSec, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediaasset.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediaasset.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(mediaasset.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(mediaasset.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(mediaasset.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(mediaasset.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(mediaasset.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploaderTable,
			Columns: []string{mediaasset.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploaderTable,
			Columns: []string{mediaasset.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaAssetUpdateOne is the builder for updating a single MediaAsset entity.
type MediaAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaAssetMutation
}

// SetUploaderID sets the "uploader_id" field.
func (_u *MediaAssetUpdateOne) SetUploaderID(v uuid.UUID) *MediaAssetUpdateOne {
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableUploaderID(v *uuid.UUID) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// ClearUploaderID clears the value of the "uploader_id" field.
func (_u *MediaAssetUpdateOne) ClearUploaderID() *MediaAssetUpdateOne {
	_u.mutation.ClearUploaderID()
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaAssetUpdateOne) SetURL(v string) *MediaAssetUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableURL(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *MediaAssetUpdateOne) SetStorageKey(v string) *MediaAssetUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableStorageKey(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *MediaAssetUpdateOne) SetFilename(v string) *MediaAssetUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableFilename(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *MediaAssetUpdateOne) SetOriginalName(v string) *MediaAssetUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableOriginalName(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdateOne) SetMimeType(v string) *MediaAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableMimeType(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *MediaAssetUpdateOne) SetAssetType(v mediaasset.AssetType) *MediaAssetUpdateOne {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableAssetType(v *mediaasset.AssetType) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *MediaAssetUpdateOne) SetSizeBytes(v int64) *MediaAssetUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableSizeBytes(v *int64) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *MediaAssetUpdateOne) AddSizeBytes(v int64) *MediaAssetUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *MediaAssetUpdateOne) SetWidth(v int) *MediaAssetUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableWidth(v *int) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *MediaAssetUpdateOne) AddWidth(v int) *MediaAssetUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *MediaAssetUpdateOne) ClearWidth() *MediaAssetUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *MediaAssetUpdateOne) SetHeight(v int) *MediaAssetUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableHeight(v *int) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *MediaAssetUpdateOne) AddHeight(v int) *MediaAssetUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *MediaAssetUpdateOne) ClearHeight() *MediaAssetUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetDurationSec sets the "duration_sec" field.
func (_u *MediaAssetUpdateOne) SetDurationSec(v float64) *MediaAssetUpdateOne {
	_u.mutation.ResetDurationSec()
	_u.mutation.SetDurationSec(v)
	return _u
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableDurationSec(v *float64) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetDurationSec(*v)
	}
	return _u
}

// AddDurationSec adds value to the "duration_sec" field.
func (_u *MediaAssetUpdateOne) AddDurationSec(v float64) *MediaAssetUpdateOne {
	_u.mutation.AddDurationSec(v)
	return _u
}

// ClearDurationSec clears the value of the "duration_sec" field.
func (_u *MediaAssetUpdateOne) ClearDurationSec() *MediaAssetUpdateOne {
	_u.mutation.ClearDurationSec()
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *MediaAssetUpdateOne) SetThumbnailURL(v string) *MediaAssetUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableThumbnailURL(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *MediaAssetUpdateOne) ClearThumbnailURL() *MediaAssetUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *MediaAssetUpdateOne) SetAltText(v string) *MediaAssetUpdateOne {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableAltText(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *MediaAssetUpdateOne) ClearAltText() *MediaAssetUpdateOne {
	_u.mutation.ClearAltText()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *MediaAssetUpdateOne) SetCaption(v string) *MediaAssetUpdateOne {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableCaption(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *MediaAssetUpdateOne) ClearCaption() *MediaAssetUpdateOne {
	_u.mutation.ClearCaption()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MediaAssetUpdateOne) SetMetadata(v map[string]interface{}) *MediaAssetUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MediaAssetUpdateOne) ClearMetadata() *MediaAssetUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *MediaAssetUpdateOne) SetUploader(v *User) *MediaAssetUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdateOne) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *MediaAssetUpdateOne) ClearUploader() *MediaAssetUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdateOne) Where(ps ...predicate.MediaAsset) *MediaAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaAssetUpdateOne) Select(field string, fields ...string) *MediaAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaAsset entity.
func (_u *MediaAssetUpdateOne) Save(ctx context.Context) (*MediaAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) SaveX(ctx context.Context) *MediaAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := mediaasset.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := mediaasset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := mediaasset.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := mediaasset.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetType(); ok {
		if err := mediaasset.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := mediaasset.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := mediaasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := mediaasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationSec(); ok {
		if err := mediaasset.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.duration_sec": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailURL(); ok {
		if err := mediaasset.ThumbnailURLValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.thumbnail_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := mediaasset.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Caption(); ok {
		if err := mediaasset.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.caption": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaAssetUpdateOne) sqlSave(ctx context.Context) (_node *MediaAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaasset.FieldID)
		for _, f := range fields {
			if !mediaasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mediaasset.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(mediaasset.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(mediaasset.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(mediaasset.FieldAssetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(mediaasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(mediaasset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(mediaasset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(mediaasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(mediaasset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(mediaasset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationSec(); ok {
		_spec.SetField(mediaasset.FieldDurationSec, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationSec(); ok {
		_spec.AddField(mediaasset.FieldDurationSec, field.TypeFloat64, value)
	}
	if _u.mutation.DurationSecCleared() {
		_spec.ClearField(mediaasset.FieldDurationSec, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediaasset.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(mediaasset.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(mediaasset.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(mediaasset.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(mediaasset.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(mediaasset.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(mediaasset.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploaderTable,
			Columns: []string{mediaasset.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploaderTable,
			Columns: []string{mediaasset.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
