// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/mediaasset"
	"krishblog/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MediaAssetCreate is the builder for creating a MediaAsset entity.
type MediaAssetCreate struct {
	config
	mutation *MediaAssetMutation
	hooks    []Hook
}

// SetUploaderID sets the "uploader_id" field.
func (_c *MediaAssetCreate) SetUploaderID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetUploaderID(v)
	return _c
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableUploaderID(v *uuid.UUID) *MediaAssetCreate {
	if v != nil {
		_c.SetUploaderID(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MediaAssetCreate) SetURL(v string) *MediaAssetCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *MediaAssetCreate) SetStorageKey(v string) *MediaAssetCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *MediaAssetCreate) SetFilename(v string) *MediaAssetCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *MediaAssetCreate) SetOriginalName(v string) *MediaAssetCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *MediaAssetCreate) SetMimeType(v string) *MediaAssetCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetAssetType sets the "asset_type" field.
func (_c *MediaAssetCreate) SetAssetType(v mediaasset.AssetType) *MediaAssetCreate {
	_c.mutation.SetAssetType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *MediaAssetCreate) SetSizeBytes(v int64) *MediaAssetCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *MediaAssetCreate) SetWidth(v int) *MediaAssetCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableWidth(v *int) *MediaAssetCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *MediaAssetCreate) SetHeight(v int) *MediaAssetCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableHeight(v *int) *MediaAssetCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetDurationSec sets the "duration_sec" field.
func (_c *MediaAssetCreate) SetDurationSec(v float64) *MediaAssetCreate {
	_c.mutation.SetDurationSec(v)
	return _c
}

// SetNillableDurationSec sets the "duration_sec" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableDurationSec(v *float64) *MediaAssetCreate {
	if v != nil {
		_c.SetDurationSec(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *MediaAssetCreate) SetThumbnailURL(v string) *MediaAssetCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableThumbnailURL(v *string) *MediaAssetCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetAltText sets the "alt_text" field.
func (_c *MediaAssetCreate) SetAltText(v string) *MediaAssetCreate {
	_c.mutation.SetAltText(v)
	return _c
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableAltText(v *string) *MediaAssetCreate {
	if v != nil {
		_c.SetAltText(*v)
	}
	return _c
}

// SetCaption sets the "caption" field.
func (_c *MediaAssetCreate) SetCaption(v string) *MediaAssetCreate {
	_c.mutation.SetCaption(v)
	return _c
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableCaption(v *string) *MediaAssetCreate {
	if v != nil {
		_c.SetCaption(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *MediaAssetCreate) SetMetadata(v map[string]interface{}) *MediaAssetCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaAssetCreate) SetCreatedAt(v time.Time) *MediaAssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableCreatedAt(v *time.Time) *MediaAssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaAssetCreate) SetID(v uuid.UUID) *MediaAssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MediaAssetCreate) SetNillableID(v *uuid.UUID) *MediaAssetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUploader sets the "uploader" edge to the User entity.
func (_c *MediaAssetCreate) SetUploader(v *User) *MediaAssetCreate {
	return _c.SetUploaderID(v.ID)
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_c *MediaAssetCreate) Mutation() *MediaAssetMutation {
	return _c.mutation
}

// Save creates the MediaAsset in the database.
func (_c *MediaAssetCreate) Save(ctx context.Context) (*MediaAsset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaAssetCreate) SaveX(ctx context.Context) *MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaAssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediaasset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mediaasset.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaAssetCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "MediaAsset.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := mediaasset.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "MediaAsset.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := mediaasset.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "MediaAsset.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := mediaasset.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "MediaAsset.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := mediaasset.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "MediaAsset.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssetType(); !ok {
		return &ValidationError{Name: "asset_type", err: errors.New(`ent: missing required field "MediaAsset.asset_type"`)}
	}
	if v, ok := _c.mutation.AssetType(); ok {
		if err := mediaasset.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.asset_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "MediaAsset.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := mediaasset.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.size_bytes": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := mediaasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.width": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := mediaasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.height": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DurationSec(); ok {
		if err := mediaasset.DurationSecValidator(v); err != nil {
			return &ValidationError{Name: "duration_sec", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.duration_sec": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ThumbnailURL(); ok {
		if err := mediaasset.ThumbnailURLValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_url", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.thumbnail_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AltText(); ok {
		if err := mediaasset.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.alt_text": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Caption(); ok {
		if err := mediaasset.CaptionValidator(v); err != nil {
			return &ValidationError{Name: "caption", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.caption": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaAsset.created_at"`)}
	}
	return nil
}

func (_c *MediaAssetCreate) sqlSave(ctx context.Context) (*MediaAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaAssetCreate) createSpec() (*MediaAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediaasset.Table, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(mediaasset.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(mediaasset.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(mediaasset.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(mediaasset.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.AssetType(); ok {
		_spec.SetField(mediaasset.FieldAssetType, field.TypeEnum, value)
		_node.AssetType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(mediaasset.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(mediaasset.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(mediaasset.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.DurationSec(); ok {
		_spec.SetField(mediaasset.FieldDurationSec, field.TypeFloat64, value)
		_node.DurationSec = &value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(mediaasset.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = &value
	}
	if value, ok := _c.mutation.AltText(); ok {
		_spec.SetField(mediaasset.FieldAltText, field.TypeString, value)
		_node.AltText = value
	}
	if value, ok := _c.mutation.Caption(); ok {
		_spec.SetField(mediaasset.FieldCaption, field.TypeString, value)
		_node.Caption = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(mediaasset.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediaasset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediaasset.UploaderTable,
			Columns: []string{mediaasset.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploaderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaAssetCreateBulk is the builder for creating many MediaAsset entities in bulk.
type MediaAssetCreateBulk struct {
	config
	err      error
	builders []*MediaAssetCreate
}

// Save creates the MediaAsset entities in the database.
func (_c *MediaAssetCreateBulk) Save(ctx context.Context) ([]*MediaAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) SaveX(ctx context.Context) []*MediaAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
