// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/analyticsevent"
	"krishblog/ent/post"
	"krishblog/ent/postblock"
	"krishblog/ent/predicate"
	"krishblog/ent/section"
	"krishblog/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSectionID sets the "section_id" field.
func (_u *PostUpdate) SetSectionID(v uuid.UUID) *PostUpdate {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSectionID(v *uuid.UUID) *PostUpdate {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdate) SetAuthorID(v uuid.UUID) *PostUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthorID(v *uuid.UUID) *PostUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdate) SetSlug(v string) *PostUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSlug(v *string) *PostUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdate) SetSummary(v string) *PostUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSummary(v *string) *PostUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdate) ClearSummary() *PostUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *PostUpdate) SetCoverImage(v string) *PostUpdate {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCoverImage(v *string) *PostUpdate {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *PostUpdate) ClearCoverImage() *PostUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetCoverImageAlt sets the "cover_image_alt" field.
func (_u *PostUpdate) SetCoverImageAlt(v string) *PostUpdate {
	_u.mutation.SetCoverImageAlt(v)
	return _u
}

// SetNillableCoverImageAlt sets the "cover_image_alt" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCoverImageAlt(v *string) *PostUpdate {
	if v != nil {
		_u.SetCoverImageAlt(*v)
	}
	return _u
}

// ClearCoverImageAlt clears the value of the "cover_image_alt" field.
func (_u *PostUpdate) ClearCoverImageAlt() *PostUpdate {
	_u.mutation.ClearCoverImageAlt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdate) SetStatus(v post.Status) *PostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdate) SetNillableStatus(v *post.Status) *PostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *PostUpdate) SetPublished(v bool) *PostUpdate {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublished(v *bool) *PostUpdate {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetReadTime sets the "read_time" field.
func (_u *PostUpdate) SetReadTime(v int) *PostUpdate {
	_u.mutation.ResetReadTime()
	_u.mutation.SetReadTime(v)
	return _u
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_u *PostUpdate) SetNillableReadTime(v *int) *PostUpdate {
	if v != nil {
		_u.SetReadTime(*v)
	}
	return _u
}

// AddReadTime adds value to the "read_time" field.
func (_u *PostUpdate) AddReadTime(v int) *PostUpdate {
	_u.mutation.AddReadTime(v)
	return _u
}

// SetWordCount sets the "word_count" field.
func (_u *PostUpdate) SetWordCount(v int) *PostUpdate {
	_u.mutation.ResetWordCount()
	_u.mutation.SetWordCount(v)
	return _u
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableWordCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetWordCount(*v)
	}
	return _u
}

// AddWordCount adds value to the "word_count" field.
func (_u *PostUpdate) AddWordCount(v int) *PostUpdate {
	_u.mutation.AddWordCount(v)
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *PostUpdate) SetIsFeatured(v bool) *PostUpdate {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsFeatured(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *PostUpdate) SetMetaTitle(v string) *PostUpdate {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableMetaTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *PostUpdate) ClearMetaTitle() *PostUpdate {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDesc sets the "meta_desc" field.
func (_u *PostUpdate) SetMetaDesc(v string) *PostUpdate {
	_u.mutation.SetMetaDesc(v)
	return _u
}

// SetNillableMetaDesc sets the "meta_desc" field if the given value is not nil.
func (_u *PostUpdate) SetNillableMetaDesc(v *string) *PostUpdate {
	if v != nil {
		_u.SetMetaDesc(*v)
	}
	return _u
}

// ClearMetaDesc clears the value of the "meta_desc" field.
func (_u *PostUpdate) ClearMetaDesc() *PostUpdate {
	_u.mutation.ClearMetaDesc()
	return _u
}

// SetOgImage sets the "og_image" field.
func (_u *PostUpdate) SetOgImage(v string) *PostUpdate {
	_u.mutation.SetOgImage(v)
	return _u
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_u *PostUpdate) SetNillableOgImage(v *string) *PostUpdate {
	if v != nil {
		_u.SetOgImage(*v)
	}
	return _u
}

// ClearOgImage clears the value of the "og_image" field.
func (_u *PostUpdate) ClearOgImage() *PostUpdate {
	_u.mutation.ClearOgImage()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdate) SetPublishedAt(v time.Time) *PostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdate) ClearPublishedAt() *PostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *PostUpdate) SetScheduledAt(v time.Time) *PostUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillableScheduledAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *PostUpdate) ClearScheduledAt() *PostUpdate {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSection sets the "section" edge to the Section entity.
func (_u *PostUpdate) SetSection(v *Section) *PostUpdate {
	return _u.SetSectionID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdate) SetAuthor(v *User) *PostUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddBlockIDs adds the "blocks" edge to the PostBlock entity by IDs.
func (_u *PostUpdate) AddBlockIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the PostBlock entity.
func (_u *PostUpdate) AddBlocks(v ...*PostBlock) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// AddAnalyticsEventIDs adds the "analytics_events" edge to the AnalyticsEvent entity by IDs.
func (_u *PostUpdate) AddAnalyticsEventIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.AddAnalyticsEventIDs(ids...)
	return _u
}

// AddAnalyticsEvents adds the "analytics_events" edges to the AnalyticsEvent entity.
func (_u *PostUpdate) AddAnalyticsEvents(v ...*AnalyticsEvent) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnalyticsEventIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *PostUpdate) ClearSection() *PostUpdate {
	_u.mutation.ClearSection()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdate) ClearAuthor() *PostUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearBlocks clears all "blocks" edges to the PostBlock entity.
func (_u *PostUpdate) ClearBlocks() *PostUpdate {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to PostBlock entities by IDs.
func (_u *PostUpdate) RemoveBlockIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to PostBlock entities.
func (_u *PostUpdate) RemoveBlocks(v ...*PostBlock) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// ClearAnalyticsEvents clears all "analytics_events" edges to the AnalyticsEvent entity.
func (_u *PostUpdate) ClearAnalyticsEvents() *PostUpdate {
	_u.mutation.ClearAnalyticsEvents()
	return _u
}

// RemoveAnalyticsEventIDs removes the "analytics_events" edge to AnalyticsEvent entities by IDs.
func (_u *PostUpdate) RemoveAnalyticsEventIDs(ids ...uuid.UUID) *PostUpdate {
	_u.mutation.RemoveAnalyticsEventIDs(ids...)
	return _u
}

// RemoveAnalyticsEvents removes "analytics_events" edges to AnalyticsEvent entities.
func (_u *PostUpdate) RemoveAnalyticsEvents(v ...*AnalyticsEvent) *PostUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnalyticsEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := post.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Post.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageAlt(); ok {
		if err := post.CoverImageAltValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_alt", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image_alt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReadTime(); ok {
		if err := post.ReadTimeValidator(v); err != nil {
			return &ValidationError{Name: "read_time", err: fmt.Errorf(`ent: validator failed for field "Post.read_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WordCount(); ok {
		if err := post.WordCountValidator(v); err != nil {
			return &ValidationError{Name: "word_count", err: fmt.Errorf(`ent: validator failed for field "Post.word_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaTitle(); ok {
		if err := post.MetaTitleValidator(v); err != nil {
			return &ValidationError{Name: "meta_title", err: fmt.Errorf(`ent: validator failed for field "Post.meta_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaDesc(); ok {
		if err := post.MetaDescValidator(v); err != nil {
			return &ValidationError{Name: "meta_desc", err: fmt.Errorf(`ent: validator failed for field "Post.meta_desc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OgImage(); ok {
		if err := post.OgImageValidator(v); err != nil {
			return &ValidationError{Name: "og_image", err: fmt.Errorf(`ent: validator failed for field "Post.og_image": %w`, err)}
		}
	}
	if _u.mutation.SectionCleared() && len(_u.mutation.SectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.section"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(post.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageAlt(); ok {
		_spec.SetField(post.FieldCoverImageAlt, field.TypeString, value)
	}
	if _u.mutation.CoverImageAltCleared() {
		_spec.ClearField(post.FieldCoverImageAlt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(post.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadTime(); ok {
		_spec.SetField(post.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadTime(); ok {
		_spec.AddField(post.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WordCount(); ok {
		_spec.SetField(post.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWordCount(); ok {
		_spec.AddField(post.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(post.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(post.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(post.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDesc(); ok {
		_spec.SetField(post.FieldMetaDesc, field.TypeString, value)
	}
	if _u.mutation.MetaDescCleared() {
		_spec.ClearField(post.FieldMetaDesc, field.TypeString)
	}
	if value, ok := _u.mutation.OgImage(); ok {
		_spec.SetField(post.FieldOgImage, field.TypeString, value)
	}
	if _u.mutation.OgImageCleared() {
		_spec.ClearField(post.FieldOgImage, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(post.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(post.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalyticsEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnalyticsEventsIDs(); len(nodes) > 0 && !_u.mutation.AnalyticsEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalyticsEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetSectionID sets the "section_id" field.
func (_u *PostUpdateOne) SetSectionID(v uuid.UUID) *PostUpdateOne {
	_u.mutation.SetSectionID(v)
	return _u
}

// SetNillableSectionID sets the "section_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSectionID(v *uuid.UUID) *PostUpdateOne {
	if v != nil {
		_u.SetSectionID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdateOne) SetAuthorID(v uuid.UUID) *PostUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthorID(v *uuid.UUID) *PostUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PostUpdateOne) SetSlug(v string) *PostUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSlug(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdateOne) SetSummary(v string) *PostUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSummary(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdateOne) ClearSummary() *PostUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *PostUpdateOne) SetCoverImage(v string) *PostUpdateOne {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCoverImage(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *PostUpdateOne) ClearCoverImage() *PostUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetCoverImageAlt sets the "cover_image_alt" field.
func (_u *PostUpdateOne) SetCoverImageAlt(v string) *PostUpdateOne {
	_u.mutation.SetCoverImageAlt(v)
	return _u
}

// SetNillableCoverImageAlt sets the "cover_image_alt" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCoverImageAlt(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCoverImageAlt(*v)
	}
	return _u
}

// ClearCoverImageAlt clears the value of the "cover_image_alt" field.
func (_u *PostUpdateOne) ClearCoverImageAlt() *PostUpdateOne {
	_u.mutation.ClearCoverImageAlt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdateOne) SetStatus(v post.Status) *PostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableStatus(v *post.Status) *PostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *PostUpdateOne) SetPublished(v bool) *PostUpdateOne {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublished(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetReadTime sets the "read_time" field.
func (_u *PostUpdateOne) SetReadTime(v int) *PostUpdateOne {
	_u.mutation.ResetReadTime()
	_u.mutation.SetReadTime(v)
	return _u
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableReadTime(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetReadTime(*v)
	}
	return _u
}

// AddReadTime adds value to the "read_time" field.
func (_u *PostUpdateOne) AddReadTime(v int) *PostUpdateOne {
	_u.mutation.AddReadTime(v)
	return _u
}

// SetWordCount sets the "word_count" field.
func (_u *PostUpdateOne) SetWordCount(v int) *PostUpdateOne {
	_u.mutation.ResetWordCount()
	_u.mutation.SetWordCount(v)
	return _u
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableWordCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetWordCount(*v)
	}
	return _u
}

// AddWordCount adds value to the "word_count" field.
func (_u *PostUpdateOne) AddWordCount(v int) *PostUpdateOne {
	_u.mutation.AddWordCount(v)
	return _u
}

// SetIsFeatured sets the "is_featured" field.
func (_u *PostUpdateOne) SetIsFeatured(v bool) *PostUpdateOne {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsFeatured(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *PostUpdateOne) SetMetaTitle(v string) *PostUpdateOne {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableMetaTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *PostUpdateOne) ClearMetaTitle() *PostUpdateOne {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDesc sets the "meta_desc" field.
func (_u *PostUpdateOne) SetMetaDesc(v string) *PostUpdateOne {
	_u.mutation.SetMetaDesc(v)
	return _u
}

// SetNillableMetaDesc sets the "meta_desc" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableMetaDesc(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetMetaDesc(*v)
	}
	return _u
}

// ClearMetaDesc clears the value of the "meta_desc" field.
func (_u *PostUpdateOne) ClearMetaDesc() *PostUpdateOne {
	_u.mutation.ClearMetaDesc()
	return _u
}

// SetOgImage sets the "og_image" field.
func (_u *PostUpdateOne) SetOgImage(v string) *PostUpdateOne {
	_u.mutation.SetOgImage(v)
	return _u
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableOgImage(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetOgImage(*v)
	}
	return _u
}

// ClearOgImage clears the value of the "og_image" field.
func (_u *PostUpdateOne) ClearOgImage() *PostUpdateOne {
	_u.mutation.ClearOgImage()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdateOne) SetPublishedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdateOne) ClearPublishedAt() *PostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *PostUpdateOne) SetScheduledAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableScheduledAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (_u *PostUpdateOne) ClearScheduledAt() *PostUpdateOne {
	_u.mutation.ClearScheduledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSection sets the "section" edge to the Section entity.
func (_u *PostUpdateOne) SetSection(v *Section) *PostUpdateOne {
	return _u.SetSectionID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *PostUpdateOne) SetAuthor(v *User) *PostUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddBlockIDs adds the "blocks" edge to the PostBlock entity by IDs.
func (_u *PostUpdateOne) AddBlockIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the PostBlock entity.
func (_u *PostUpdateOne) AddBlocks(v ...*PostBlock) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// AddAnalyticsEventIDs adds the "analytics_events" edge to the AnalyticsEvent entity by IDs.
func (_u *PostUpdateOne) AddAnalyticsEventIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.AddAnalyticsEventIDs(ids...)
	return _u
}

// AddAnalyticsEvents adds the "analytics_events" edges to the AnalyticsEvent entity.
func (_u *PostUpdateOne) AddAnalyticsEvents(v ...*AnalyticsEvent) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnalyticsEventIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearSection clears the "section" edge to the Section entity.
func (_u *PostUpdateOne) ClearSection() *PostUpdateOne {
	_u.mutation.ClearSection()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *PostUpdateOne) ClearAuthor() *PostUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearBlocks clears all "blocks" edges to the PostBlock entity.
func (_u *PostUpdateOne) ClearBlocks() *PostUpdateOne {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to PostBlock entities by IDs.
func (_u *PostUpdateOne) RemoveBlockIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to PostBlock entities.
func (_u *PostUpdateOne) RemoveBlocks(v ...*PostBlock) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// ClearAnalyticsEvents clears all "analytics_events" edges to the AnalyticsEvent entity.
func (_u *PostUpdateOne) ClearAnalyticsEvents() *PostUpdateOne {
	_u.mutation.ClearAnalyticsEvents()
	return _u
}

// RemoveAnalyticsEventIDs removes the "analytics_events" edge to AnalyticsEvent entities by IDs.
func (_u *PostUpdateOne) RemoveAnalyticsEventIDs(ids ...uuid.UUID) *PostUpdateOne {
	_u.mutation.RemoveAnalyticsEventIDs(ids...)
	return _u
}

// RemoveAnalyticsEvents removes "analytics_events" edges to AnalyticsEvent entities.
func (_u *PostUpdateOne) RemoveAnalyticsEvents(v ...*AnalyticsEvent) *PostUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnalyticsEventIDs(ids...)
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := post.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Post.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImageAlt(); ok {
		if err := post.CoverImageAltValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_alt", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image_alt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReadTime(); ok {
		if err := post.ReadTimeValidator(v); err != nil {
			return &ValidationError{Name: "read_time", err: fmt.Errorf(`ent: validator failed for field "Post.read_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WordCount(); ok {
		if err := post.WordCountValidator(v); err != nil {
			return &ValidationError{Name: "word_count", err: fmt.Errorf(`ent: validator failed for field "Post.word_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaTitle(); ok {
		if err := post.MetaTitleValidator(v); err != nil {
			return &ValidationError{Name: "meta_title", err: fmt.Errorf(`ent: validator failed for field "Post.meta_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaDesc(); ok {
		if err := post.MetaDescValidator(v); err != nil {
			return &ValidationError{Name: "meta_desc", err: fmt.Errorf(`ent: validator failed for field "Post.meta_desc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OgImage(); ok {
		if err := post.OgImageValidator(v); err != nil {
			return &ValidationError{Name: "og_image", err: fmt.Errorf(`ent: validator failed for field "Post.og_image": %w`, err)}
		}
	}
	if _u.mutation.SectionCleared() && len(_u.mutation.SectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.section"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.author"`)
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(post.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageAlt(); ok {
		_spec.SetField(post.FieldCoverImageAlt, field.TypeString, value)
	}
	if _u.mutation.CoverImageAltCleared() {
		_spec.ClearField(post.FieldCoverImageAlt, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(post.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadTime(); ok {
		_spec.SetField(post.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReadTime(); ok {
		_spec.AddField(post.FieldReadTime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WordCount(); ok {
		_spec.SetField(post.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWordCount(); ok {
		_spec.AddField(post.FieldWordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(post.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(post.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(post.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDesc(); ok {
		_spec.SetField(post.FieldMetaDesc, field.TypeString, value)
	}
	if _u.mutation.MetaDescCleared() {
		_spec.ClearField(post.FieldMetaDesc, field.TypeString)
	}
	if value, ok := _u.mutation.OgImage(); ok {
		_spec.SetField(post.FieldOgImage, field.TypeString, value)
	}
	if _u.mutation.OgImageCleared() {
		_spec.ClearField(post.FieldOgImage, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(post.FieldScheduledAt, field.TypeTime, value)
	}
	if _u.mutation.ScheduledAtCleared() {
		_spec.ClearField(post.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalyticsEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnalyticsEventsIDs(); len(nodes) > 0 && !_u.mutation.AnalyticsEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalyticsEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
