// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/analyticsevent"
	"krishblog/ent/post"
	"krishblog/ent/postblock"
	"krishblog/ent/section"
	"krishblog/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetSectionID sets the "section_id" field.
func (_c *PostCreate) SetSectionID(v uuid.UUID) *PostCreate {
	_c.mutation.SetSectionID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *PostCreate) SetAuthorID(v uuid.UUID) *PostCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PostCreate) SetSlug(v string) *PostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *PostCreate) SetSummary(v string) *PostCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *PostCreate) SetNillableSummary(v *string) *PostCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetCoverImage sets the "cover_image" field.
func (_c *PostCreate) SetCoverImage(v string) *PostCreate {
	_c.mutation.SetCoverImage(v)
	return _c
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_c *PostCreate) SetNillableCoverImage(v *string) *PostCreate {
	if v != nil {
		_c.SetCoverImage(*v)
	}
	return _c
}

// SetCoverImageAlt sets the "cover_image_alt" field.
func (_c *PostCreate) SetCoverImageAlt(v string) *PostCreate {
	_c.mutation.SetCoverImageAlt(v)
	return _c
}

// SetNillableCoverImageAlt sets the "cover_image_alt" field if the given value is not nil.
func (_c *PostCreate) SetNillableCoverImageAlt(v *string) *PostCreate {
	if v != nil {
		_c.SetCoverImageAlt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PostCreate) SetStatus(v post.Status) *PostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PostCreate) SetNillableStatus(v *post.Status) *PostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPublished sets the "published" field.
func (_c *PostCreate) SetPublished(v bool) *PostCreate {
	_c.mutation.SetPublished(v)
	return _c
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublished(v *bool) *PostCreate {
	if v != nil {
		_c.SetPublished(*v)
	}
	return _c
}

// SetReadTime sets the "read_time" field.
func (_c *PostCreate) SetReadTime(v int) *PostCreate {
	_c.mutation.SetReadTime(v)
	return _c
}

// SetNillableReadTime sets the "read_time" field if the given value is not nil.
func (_c *PostCreate) SetNillableReadTime(v *int) *PostCreate {
	if v != nil {
		_c.SetReadTime(*v)
	}
	return _c
}

// SetWordCount sets the "word_count" field.
func (_c *PostCreate) SetWordCount(v int) *PostCreate {
	_c.mutation.SetWordCount(v)
	return _c
}

// SetNillableWordCount sets the "word_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableWordCount(v *int) *PostCreate {
	if v != nil {
		_c.SetWordCount(*v)
	}
	return _c
}

// SetIsFeatured sets the "is_featured" field.
func (_c *PostCreate) SetIsFeatured(v bool) *PostCreate {
	_c.mutation.SetIsFeatured(v)
	return _c
}

// SetNillableIsFeatured sets the "is_featured" field if the given value is not nil.
func (_c *PostCreate) SetNillableIsFeatured(v *bool) *PostCreate {
	if v != nil {
		_c.SetIsFeatured(*v)
	}
	return _c
}

// SetMetaTitle sets the "meta_title" field.
func (_c *PostCreate) SetMetaTitle(v string) *PostCreate {
	_c.mutation.SetMetaTitle(v)
	return _c
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_c *PostCreate) SetNillableMetaTitle(v *string) *PostCreate {
	if v != nil {
		_c.SetMetaTitle(*v)
	}
	return _c
}

// SetMetaDesc sets the "meta_desc" field.
func (_c *PostCreate) SetMetaDesc(v string) *PostCreate {
	_c.mutation.SetMetaDesc(v)
	return _c
}

// SetNillableMetaDesc sets the "meta_desc" field if the given value is not nil.
func (_c *PostCreate) SetNillableMetaDesc(v *string) *PostCreate {
	if v != nil {
		_c.SetMetaDesc(*v)
	}
	return _c
}

// SetOgImage sets the "og_image" field.
func (_c *PostCreate) SetOgImage(v string) *PostCreate {
	_c.mutation.SetOgImage(v)
	return _c
}

// SetNillableOgImage sets the "og_image" field if the given value is not nil.
func (_c *PostCreate) SetNillableOgImage(v *string) *PostCreate {
	if v != nil {
		_c.SetOgImage(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PostCreate) SetPublishedAt(v time.Time) *PostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *PostCreate) SetScheduledAt(v time.Time) *PostCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableScheduledAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v uuid.UUID) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PostCreate) SetNillableID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSection sets the "section" edge to the Section entity.
func (_c *PostCreate) SetSection(v *Section) *PostCreate {
	return _c.SetSectionID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *PostCreate) SetAuthor(v *User) *PostCreate {
	return _c.SetAuthorID(v.ID)
}

// AddBlockIDs adds the "blocks" edge to the PostBlock entity by IDs.
func (_c *PostCreate) AddBlockIDs(ids ...uuid.UUID) *PostCreate {
	_c.mutation.AddBlockIDs(ids...)
	return _c
}

// AddBlocks adds the "blocks" edges to the PostBlock entity.
func (_c *PostCreate) AddBlocks(v ...*PostBlock) *PostCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBlockIDs(ids...)
}

// AddAnalyticsEventIDs adds the "analytics_events" edge to the AnalyticsEvent entity by IDs.
func (_c *PostCreate) AddAnalyticsEventIDs(ids ...uuid.UUID) *PostCreate {
	_c.mutation.AddAnalyticsEventIDs(ids...)
	return _c
}

// AddAnalyticsEvents adds the "analytics_events" edges to the AnalyticsEvent entity.
func (_c *PostCreate) AddAnalyticsEvents(v ...*AnalyticsEvent) *PostCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnalyticsEventIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := post.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Published(); !ok {
		v := post.DefaultPublished
		_c.mutation.SetPublished(v)
	}
	if _, ok := _c.mutation.ReadTime(); !ok {
		v := post.DefaultReadTime
		_c.mutation.SetReadTime(v)
	}
	if _, ok := _c.mutation.WordCount(); !ok {
		v := post.DefaultWordCount
		_c.mutation.SetWordCount(v)
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		v := post.DefaultIsFeatured
		_c.mutation.SetIsFeatured(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := post.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.SectionID(); !ok {
		return &ValidationError{Name: "section_id", err: errors.New(`ent: missing required field "Post.section_id"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Post.author_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Post.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := post.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Post.slug": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverImageAlt(); ok {
		if err := post.CoverImageAltValidator(v); err != nil {
			return &ValidationError{Name: "cover_image_alt", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image_alt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Post.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Published(); !ok {
		return &ValidationError{Name: "published", err: errors.New(`ent: missing required field "Post.published"`)}
	}
	if _, ok := _c.mutation.ReadTime(); !ok {
		return &ValidationError{Name: "read_time", err: errors.New(`ent: missing required field "Post.read_time"`)}
	}
	if v, ok := _c.mutation.ReadTime(); ok {
		if err := post.ReadTimeValidator(v); err != nil {
			return &ValidationError{Name: "read_time", err: fmt.Errorf(`ent: validator failed for field "Post.read_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WordCount(); !ok {
		return &ValidationError{Name: "word_count", err: errors.New(`ent: missing required field "Post.word_count"`)}
	}
	if v, ok := _c.mutation.WordCount(); ok {
		if err := post.WordCountValidator(v); err != nil {
			return &ValidationError{Name: "word_count", err: fmt.Errorf(`ent: validator failed for field "Post.word_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsFeatured(); !ok {
		return &ValidationError{Name: "is_featured", err: errors.New(`ent: missing required field "Post.is_featured"`)}
	}
	if v, ok := _c.mutation.MetaTitle(); ok {
		if err := post.MetaTitleValidator(v); err != nil {
			return &ValidationError{Name: "meta_title", err: fmt.Errorf(`ent: validator failed for field "Post.meta_title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MetaDesc(); ok {
		if err := post.MetaDescValidator(v); err != nil {
			return &ValidationError{Name: "meta_desc", err: fmt.Errorf(`ent: validator failed for field "Post.meta_desc": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OgImage(); ok {
		if err := post.OgImageValidator(v); err != nil {
			return &ValidationError{Name: "og_image", err: fmt.Errorf(`ent: validator failed for field "Post.og_image": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	if len(_c.mutation.SectionIDs()) == 0 {
		return &ValidationError{Name: "section", err: errors.New(`ent: missing required edge "Post.section"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "Post.author"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
		_node.CoverImage = &value
	}
	if value, ok := _c.mutation.CoverImageAlt(); ok {
		_spec.SetField(post.FieldCoverImageAlt, field.TypeString, value)
		_node.CoverImageAlt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Published(); ok {
		_spec.SetField(post.FieldPublished, field.TypeBool, value)
		_node.Published = value
	}
	if value, ok := _c.mutation.ReadTime(); ok {
		_spec.SetField(post.FieldReadTime, field.TypeInt, value)
		_node.ReadTime = value
	}
	if value, ok := _c.mutation.WordCount(); ok {
		_spec.SetField(post.FieldWordCount, field.TypeInt, value)
		_node.WordCount = value
	}
	if value, ok := _c.mutation.IsFeatured(); ok {
		_spec.SetField(post.FieldIsFeatured, field.TypeBool, value)
		_node.IsFeatured = value
	}
	if value, ok := _c.mutation.MetaTitle(); ok {
		_spec.SetField(post.FieldMetaTitle, field.TypeString, value)
		_node.MetaTitle = value
	}
	if value, ok := _c.mutation.MetaDesc(); ok {
		_spec.SetField(post.FieldMetaDesc, field.TypeString, value)
		_node.MetaDesc = value
	}
	if value, ok := _c.mutation.OgImage(); ok {
		_spec.SetField(post.FieldOgImage, field.TypeString, value)
		_node.OgImage = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(post.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.SectionTable,
			Columns: []string{post.SectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.BlocksTable,
			Columns: []string{post.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnalyticsEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.AnalyticsEventsTable,
			Columns: []string{post.AnalyticsEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analyticsevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
