// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"krishblog/ent/post"
	"krishblog/ent/postblock"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PostBlock is the model entity for the PostBlock schema.
type PostBlock struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Owning post
	PostID uuid.UUID `json:"post_id,omitempty"`
	// Block renderer type
	Type postblock.Type `json:"type,omitempty"`
	// Primary text content (markdown or plain text depending on type)
	Content string `json:"content,omitempty"`
	// Type-specific attributes — e.g. {lang: 'go'} for code, {level: 2} for heading
	Attrs map[string]interface{} `json:"attrs,omitempty"`
	// Zero-based display order within the post
	Position int `json:"position,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostBlockQuery when eager-loading is set.
	Edges        PostBlockEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostBlockEdges holds the relations/edges for other nodes in the graph.
type PostBlockEdges struct {
	// Post this block belongs to
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostBlockEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostBlock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postblock.FieldAttrs:
			values[i] = new([]byte)
		case postblock.FieldPosition:
			values[i] = new(sql.NullInt64)
		case postblock.FieldType, postblock.FieldContent:
			values[i] = new(sql.NullString)
		case postblock.FieldID, postblock.FieldPostID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostBlock fields.
func (_m *PostBlock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postblock.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case postblock.FieldPostID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				_m.PostID = *value
			}
		case postblock.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = postblock.Type(value.String)
			}
		case postblock.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case postblock.FieldAttrs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attrs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Attrs); err != nil {
					return fmt.Errorf("unmarshal field attrs: %w", err)
				}
			}
		case postblock.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostBlock.
// This includes values selected through modifiers, order, etc.
func (_m *PostBlock) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostBlock entity.
func (_m *PostBlock) QueryPost() *PostQuery {
	return NewPostBlockClient(_m.config).QueryPost(_m)
}

// Update returns a builder for updating this PostBlock.
// Note that you need to call PostBlock.Unwrap() before calling this method if this PostBlock
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostBlock) Update() *PostBlockUpdateOne {
	return NewPostBlockClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostBlock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostBlock) Unwrap() *PostBlock {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostBlock is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostBlock) String() string {
	var builder strings.Builder
	builder.WriteString("PostBlock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("attrs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attrs))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteByte(')')
	return builder.String()
}

// PostBlocks is a parsable slice of PostBlock.
type PostBlocks []*PostBlock
