// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/post"
	"krishblog/ent/postblock"
	"krishblog/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostBlockUpdate is the builder for updating PostBlock entities.
type PostBlockUpdate struct {
	config
	hooks    []Hook
	mutation *PostBlockMutation
}

// Where appends a list predicates to the PostBlockUpdate builder.
func (_u *PostBlockUpdate) Where(ps ...predicate.PostBlock) *PostBlockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *PostBlockUpdate) SetPostID(v uuid.UUID) *PostBlockUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostBlockUpdate) SetNillablePostID(v *uuid.UUID) *PostBlockUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PostBlockUpdate) SetType(v postblock.Type) *PostBlockUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PostBlockUpdate) SetNillableType(v *postblock.Type) *PostBlockUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostBlockUpdate) SetContent(v string) *PostBlockUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostBlockUpdate) SetNillableContent(v *string) *PostBlockUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *PostBlockUpdate) ClearContent() *PostBlockUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetAttrs sets the "attrs" field.
func (_u *PostBlockUpdate) SetAttrs(v map[string]interface{}) *PostBlockUpdate {
	_u.mutation.SetAttrs(v)
	return _u
}

// ClearAttrs clears the value of the "attrs" field.
func (_u *PostBlockUpdate) ClearAttrs() *PostBlockUpdate {
	_u.mutation.ClearAttrs()
	return _u
}

// SetPosition sets the "position" field.
func (_u *PostBlockUpdate) SetPosition(v int) *PostBlockUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PostBlockUpdate) SetNillablePosition(v *int) *PostBlockUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PostBlockUpdate) AddPosition(v int) *PostBlockUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostBlockUpdate) SetPost(v *Post) *PostBlockUpdate {
	return _u.SetPostID(v.ID)
}

// Mutation returns the PostBlockMutation object of the builder.
func (_u *PostBlockUpdate) Mutation() *PostBlockMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostBlockUpdate) ClearPost() *PostBlockUpdate {
	_u.mutation.ClearPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostBlockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostBlockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostBlockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostBlockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostBlockUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := postblock.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PostBlock.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Position(); ok {
		if err := postblock.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "PostBlock.position": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostBlock.post"`)
	}
	return nil
}

func (_u *PostBlockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postblock.Table, postblock.Columns, sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(postblock.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(postblock.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(postblock.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Attrs(); ok {
		_spec.SetField(postblock.FieldAttrs, field.TypeJSON, value)
	}
	if _u.mutation.AttrsCleared() {
		_spec.ClearField(postblock.FieldAttrs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(postblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(postblock.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postblock.PostTable,
			Columns: []string{postblock.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postblock.PostTable,
			Columns: []string{postblock.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostBlockUpdateOne is the builder for updating a single PostBlock entity.
type PostBlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostBlockMutation
}

// SetPostID sets the "post_id" field.
func (_u *PostBlockUpdateOne) SetPostID(v uuid.UUID) *PostBlockUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostBlockUpdateOne) SetNillablePostID(v *uuid.UUID) *PostBlockUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PostBlockUpdateOne) SetType(v postblock.Type) *PostBlockUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PostBlockUpdateOne) SetNillableType(v *postblock.Type) *PostBlockUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostBlockUpdateOne) SetContent(v string) *PostBlockUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostBlockUpdateOne) SetNillableContent(v *string) *PostBlockUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *PostBlockUpdateOne) ClearContent() *PostBlockUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetAttrs sets the "attrs" field.
func (_u *PostBlockUpdateOne) SetAttrs(v map[string]interface{}) *PostBlockUpdateOne {
	_u.mutation.SetAttrs(v)
	return _u
}

// ClearAttrs clears the value of the "attrs" field.
func (_u *PostBlockUpdateOne) ClearAttrs() *PostBlockUpdateOne {
	_u.mutation.ClearAttrs()
	return _u
}

// SetPosition sets the "position" field.
func (_u *PostBlockUpdateOne) SetPosition(v int) *PostBlockUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *PostBlockUpdateOne) SetNillablePosition(v *int) *PostBlockUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *PostBlockUpdateOne) AddPosition(v int) *PostBlockUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostBlockUpdateOne) SetPost(v *Post) *PostBlockUpdateOne {
	return _u.SetPostID(v.ID)
}

// Mutation returns the PostBlockMutation object of the builder.
func (_u *PostBlockUpdateOne) Mutation() *PostBlockMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostBlockUpdateOne) ClearPost() *PostBlockUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// Where appends a list predicates to the PostBlockUpdate builder.
func (_u *PostBlockUpdateOne) Where(ps ...predicate.PostBlock) *PostBlockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostBlockUpdateOne) Select(field string, fields ...string) *PostBlockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostBlock entity.
func (_u *PostBlockUpdateOne) Save(ctx context.Context) (*PostBlock, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostBlockUpdateOne) SaveX(ctx context.Context) *PostBlock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostBlockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostBlockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostBlockUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := postblock.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PostBlock.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Position(); ok {
		if err := postblock.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "PostBlock.position": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostBlock.post"`)
	}
	return nil
}

func (_u *PostBlockUpdateOne) sqlSave(ctx context.Context) (_node *PostBlock, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postblock.Table, postblock.Columns, sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostBlock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postblock.FieldID)
		for _, f := range fields {
			if !postblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(postblock.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(postblock.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(postblock.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Attrs(); ok {
		_spec.SetField(postblock.FieldAttrs, field.TypeJSON, value)
	}
	if _u.mutation.AttrsCleared() {
		_spec.ClearField(postblock.FieldAttrs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(postblock.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(postblock.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postblock.PostTable,
			Columns: []string{postblock.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postblock.PostTable,
			Columns: []string{postblock.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostBlock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
