// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"krishblog/ent/postblock"
	"krishblog/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostBlockDelete is the builder for deleting a PostBlock entity.
type PostBlockDelete struct {
	config
	hooks    []Hook
	mutation *PostBlockMutation
}

// Where appends a list predicates to the PostBlockDelete builder.
func (_d *PostBlockDelete) Where(ps ...predicate.PostBlock) *PostBlockDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PostBlockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostBlockDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PostBlockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postblock.Table, sqlgraph.NewFieldSpec(postblock.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PostBlockDeleteOne is the builder for deleting a single PostBlock entity.
type PostBlockDeleteOne struct {
	_d *PostBlockDelete
}

// Where appends a list predicates to the PostBlockDelete builder.
func (_d *PostBlockDeleteOne) Where(ps ...predicate.PostBlock) *PostBlockDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PostBlockDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postblock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostBlockDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
