// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"krishblog/ent/post"
	"krishblog/ent/predicate"
	"krishblog/ent/section"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SectionUpdate is the builder for updating Section entities.
type SectionUpdate struct {
	config
	hooks    []Hook
	mutation *SectionMutation
}

// Where appends a list predicates to the SectionUpdate builder.
func (_u *SectionUpdate) Where(ps ...predicate.Section) *SectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SectionUpdate) SetName(v string) *SectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableName(v *string) *SectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SectionUpdate) SetSlug(v string) *SectionUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableSlug(v *string) *SectionUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SectionUpdate) SetDescription(v string) *SectionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableDescription(v *string) *SectionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SectionUpdate) ClearDescription() *SectionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetThemeColor sets the "theme_color" field.
func (_u *SectionUpdate) SetThemeColor(v string) *SectionUpdate {
	_u.mutation.SetThemeColor(v)
	return _u
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableThemeColor(v *string) *SectionUpdate {
	if v != nil {
		_u.SetThemeColor(*v)
	}
	return _u
}

// ClearThemeColor clears the value of the "theme_color" field.
func (_u *SectionUpdate) ClearThemeColor() *SectionUpdate {
	_u.mutation.ClearThemeColor()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *SectionUpdate) SetCoverImage(v string) *SectionUpdate {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableCoverImage(v *string) *SectionUpdate {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *SectionUpdate) ClearCoverImage() *SectionUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *SectionUpdate) SetMetaTitle(v string) *SectionUpdate {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableMetaTitle(v *string) *SectionUpdate {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *SectionUpdate) ClearMetaTitle() *SectionUpdate {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDesc sets the "meta_desc" field.
func (_u *SectionUpdate) SetMetaDesc(v string) *SectionUpdate {
	_u.mutation.SetMetaDesc(v)
	return _u
}

// SetNillableMetaDesc sets the "meta_desc" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableMetaDesc(v *string) *SectionUpdate {
	if v != nil {
		_u.SetMetaDesc(*v)
	}
	return _u
}

// ClearMetaDesc clears the value of the "meta_desc" field.
func (_u *SectionUpdate) ClearMetaDesc() *SectionUpdate {
	_u.mutation.ClearMetaDesc()
	return _u
}

// SetLayout sets the "layout" field.
func (_u *SectionUpdate) SetLayout(v section.Layout) *SectionUpdate {
	_u.mutation.SetLayout(v)
	return _u
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableLayout(v *section.Layout) *SectionUpdate {
	if v != nil {
		_u.SetLayout(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *SectionUpdate) SetIsActive(v bool) *SectionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableIsActive(v *bool) *SectionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SectionUpdate) SetSortOrder(v int) *SectionUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SectionUpdate) SetNillableSortOrder(v *int) *SectionUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SectionUpdate) AddSortOrder(v int) *SectionUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *SectionUpdate) SetSettings(v map[string]interface{}) *SectionUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *SectionUpdate) ClearSettings() *SectionUpdate {
	_u.mutation.ClearSettings()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectionUpdate) SetUpdatedAt(v time.Time) *SectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *SectionUpdate) AddPostIDs(ids ...uuid.UUID) *SectionUpdate {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *SectionUpdate) AddPosts(v ...*Post) *SectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (_u *SectionUpdate) Mutation() *SectionMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *SectionUpdate) ClearPosts() *SectionUpdate {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *SectionUpdate) RemovePostIDs(ids ...uuid.UUID) *SectionUpdate {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *SectionUpdate) RemovePosts(v ...*Post) *SectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := section.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := section.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Section.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := section.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Section.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := section.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Section.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThemeColor(); ok {
		if err := section.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Section.theme_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := section.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Section.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaTitle(); ok {
		if err := section.MetaTitleValidator(v); err != nil {
			return &ValidationError{Name: "meta_title", err: fmt.Errorf(`ent: validator failed for field "Section.meta_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaDesc(); ok {
		if err := section.MetaDescValidator(v); err != nil {
			return &ValidationError{Name: "meta_desc", err: fmt.Errorf(`ent: validator failed for field "Section.meta_desc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Layout(); ok {
		if err := section.LayoutValidator(v); err != nil {
			return &ValidationError{Name: "layout", err: fmt.Errorf(`ent: validator failed for field "Section.layout": %w`, err)}
		}
	}
	return nil
}

func (_u *SectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(section.Table, section.Columns, sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(section.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(section.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(section.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(section.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ThemeColor(); ok {
		_spec.SetField(section.FieldThemeColor, field.TypeString, value)
	}
	if _u.mutation.ThemeColorCleared() {
		_spec.ClearField(section.FieldThemeColor, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(section.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(section.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(section.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(section.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDesc(); ok {
		_spec.SetField(section.FieldMetaDesc, field.TypeString, value)
	}
	if _u.mutation.MetaDescCleared() {
		_spec.ClearField(section.FieldMetaDesc, field.TypeString)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(section.FieldLayout, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(section.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(section.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(section.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(section.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(section.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(section.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{section.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SectionUpdateOne is the builder for updating a single Section entity.
type SectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SectionMutation
}

// SetName sets the "name" field.
func (_u *SectionUpdateOne) SetName(v string) *SectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableName(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SectionUpdateOne) SetSlug(v string) *SectionUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableSlug(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SectionUpdateOne) SetDescription(v string) *SectionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableDescription(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SectionUpdateOne) ClearDescription() *SectionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetThemeColor sets the "theme_color" field.
func (_u *SectionUpdateOne) SetThemeColor(v string) *SectionUpdateOne {
	_u.mutation.SetThemeColor(v)
	return _u
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableThemeColor(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetThemeColor(*v)
	}
	return _u
}

// ClearThemeColor clears the value of the "theme_color" field.
func (_u *SectionUpdateOne) ClearThemeColor() *SectionUpdateOne {
	_u.mutation.ClearThemeColor()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *SectionUpdateOne) SetCoverImage(v string) *SectionUpdateOne {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableCoverImage(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *SectionUpdateOne) ClearCoverImage() *SectionUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetMetaTitle sets the "meta_title" field.
func (_u *SectionUpdateOne) SetMetaTitle(v string) *SectionUpdateOne {
	_u.mutation.SetMetaTitle(v)
	return _u
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableMetaTitle(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetMetaTitle(*v)
	}
	return _u
}

// ClearMetaTitle clears the value of the "meta_title" field.
func (_u *SectionUpdateOne) ClearMetaTitle() *SectionUpdateOne {
	_u.mutation.ClearMetaTitle()
	return _u
}

// SetMetaDesc sets the "meta_desc" field.
func (_u *SectionUpdateOne) SetMetaDesc(v string) *SectionUpdateOne {
	_u.mutation.SetMetaDesc(v)
	return _u
}

// SetNillableMetaDesc sets the "meta_desc" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableMetaDesc(v *string) *SectionUpdateOne {
	if v != nil {
		_u.SetMetaDesc(*v)
	}
	return _u
}

// ClearMetaDesc clears the value of the "meta_desc" field.
func (_u *SectionUpdateOne) ClearMetaDesc() *SectionUpdateOne {
	_u.mutation.ClearMetaDesc()
	return _u
}

// SetLayout sets the "layout" field.
func (_u *SectionUpdateOne) SetLayout(v section.Layout) *SectionUpdateOne {
	_u.mutation.SetLayout(v)
	return _u
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableLayout(v *section.Layout) *SectionUpdateOne {
	if v != nil {
		_u.SetLayout(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *SectionUpdateOne) SetIsActive(v bool) *SectionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableIsActive(v *bool) *SectionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SectionUpdateOne) SetSortOrder(v int) *SectionUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SectionUpdateOne) SetNillableSortOrder(v *int) *SectionUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SectionUpdateOne) AddSortOrder(v int) *SectionUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetSettings sets the "settings" field.
func (_u *SectionUpdateOne) SetSettings(v map[string]interface{}) *SectionUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *SectionUpdateOne) ClearSettings() *SectionUpdateOne {
	_u.mutation.ClearSettings()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectionUpdateOne) SetUpdatedAt(v time.Time) *SectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *SectionUpdateOne) AddPostIDs(ids ...uuid.UUID) *SectionUpdateOne {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *SectionUpdateOne) AddPosts(v ...*Post) *SectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// Mutation returns the SectionMutation object of the builder.
func (_u *SectionUpdateOne) Mutation() *SectionMutation {
	return _u.mutation
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *SectionUpdateOne) ClearPosts() *SectionUpdateOne {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *SectionUpdateOne) RemovePostIDs(ids ...uuid.UUID) *SectionUpdateOne {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *SectionUpdateOne) RemovePosts(v ...*Post) *SectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// Where appends a list predicates to the SectionUpdate builder.
func (_u *SectionUpdateOne) Where(ps ...predicate.Section) *SectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SectionUpdateOne) Select(field string, fields ...string) *SectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Section entity.
func (_u *SectionUpdateOne) Save(ctx context.Context) (*Section, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectionUpdateOne) SaveX(ctx context.Context) *Section {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := section.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := section.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Section.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := section.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Section.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := section.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Section.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThemeColor(); ok {
		if err := section.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Section.theme_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := section.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Section.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaTitle(); ok {
		if err := section.MetaTitleValidator(v); err != nil {
			return &ValidationError{Name: "meta_title", err: fmt.Errorf(`ent: validator failed for field "Section.meta_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetaDesc(); ok {
		if err := section.MetaDescValidator(v); err != nil {
			return &ValidationError{Name: "meta_desc", err: fmt.Errorf(`ent: validator failed for field "Section.meta_desc": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Layout(); ok {
		if err := section.LayoutValidator(v); err != nil {
			return &ValidationError{Name: "layout", err: fmt.Errorf(`ent: validator failed for field "Section.layout": %w`, err)}
		}
	}
	return nil
}

func (_u *SectionUpdateOne) sqlSave(ctx context.Context) (_node *Section, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(section.Table, section.Columns, sqlgraph.NewFieldSpec(section.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Section.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, section.FieldID)
		for _, f := range fields {
			if !section.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != section.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(section.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(section.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(section.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(section.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ThemeColor(); ok {
		_spec.SetField(section.FieldThemeColor, field.TypeString, value)
	}
	if _u.mutation.ThemeColorCleared() {
		_spec.ClearField(section.FieldThemeColor, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(section.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(section.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.MetaTitle(); ok {
		_spec.SetField(section.FieldMetaTitle, field.TypeString, value)
	}
	if _u.mutation.MetaTitleCleared() {
		_spec.ClearField(section.FieldMetaTitle, field.TypeString)
	}
	if value, ok := _u.mutation.MetaDesc(); ok {
		_spec.SetField(section.FieldMetaDesc, field.TypeString, value)
	}
	if _u.mutation.MetaDescCleared() {
		_spec.ClearField(section.FieldMetaDesc, field.TypeString)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(section.FieldLayout, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(section.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(section.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(section.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(section.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(section.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(section.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   section.PostsTable,
			Columns: []string{section.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Section{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{section.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
