// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AnalyticsEvent is the predicate function for analyticsevent builders.
type AnalyticsEvent func(*sql.Selector)

// MediaAsset is the predicate function for mediaasset builders.
type MediaAsset func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostBlock is the predicate function for postblock builders.
type PostBlock func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
